workspace/ts100/src/Strings.c
Hi Ralim:
I've done the translation of all software except the short names of system, because it will be better if the short names are the same on all languages.
Regards.
=> Translated strings to es_ES

workspace/ts100/src/Strings.c
I've added the french translation for all the strings
=> Added french language

workspace/ts100/src/Strings.c
Thanks for the awesome work with the firmware.
I'm unable to build & test but I believe these are the changes needed for Swedish to work, I'm not _really_ a C-guy, sorry.
=> Swedish translation

README.md
Added link to a french article with the instructions
=> Added link to a french article

workspace/TS100/src/Translation.c
Hi!
Let me first thank you for your work on this excellent firmware replacement. I really appreciate it!
I did just update the german strings in Translation.c
I hope that I did get everything right because I had to look up the handling for the autostart mode in gui.cpp. It looks like it's handled as a boolean value now, while the other translations mention three possible states.
=> Update german translation in Translation.c

Bootup Logo/python_logo_converter/img2ts100.py
Made sure this code works on Python3.  General PEP8 cleanup.  
Summary of changes:
1) Using Python3 floor_division (//) which is equivalent to Python2 division if using ints
2) Converted to format strings from %
3) Converted Exceptions and try/except to modern format
4) Whitespace and misc PEP8 stuff
Love the codebase.  Thanks for your hard work!  😄
=> Python3 and PEP8

workspace/TS100/src/OLED.cpp
=> Fix oled draw c2 section

workspace/TS100/inc/Translation.h, workspace/TS100/src/Translation.c
Added czech translation (locale cs_CZ)
=> Add czech translation

workspace/TS100/src/Translation.c
More readable double lined short names. Formatted whitespaces of english text.
=> LANG_CS_CZ Updated menu items to double lines

workspace/TS100/inc/Translation.h, workspace/TS100/inc/gui.h, workspace/TS100/inc/main.hpp, workspace/TS100/src/Translation.c, workspace/TS100/src/gui.cpp, workspace/TS100/src/main.cpp
Unify behavior of menu items with questions/warnings
=> Fix reset settings menu item resolves #144

workspace/TS100/src/Translation.c
=> [FIX] italian translation

workspace/TS100/src/Translation.c
Since #173 is merged, I improve french translation to use all utf-8 chars
=> French translation - improvements

workspace/TS100/src/Translation.c
- updated to match current codebase
- added diacritics
=> Update translation cs_CZ

Bootup Logo/Logo GUI/TS100 Logo Editor/TS100 Logo Editor/Form1.cs, workspace/TS100/src/Translation.c, workspace/TS100/src/gui.cpp
- comments in translations state wrong max lengths
- fixed comments in gui.cpp
=> Fix comments (translation max lengths)

workspace/TS100/src/Translation.cpp
see title.
Edit: I wasn't really sure about the allowed length of "SolderingAdvancedPowerPrompt". From a short look at the display with the english firmware I'm sure it's short enough, but the exact allowed length would be useful here.
=> Updated german translation

workspace/TS100/src/Translation.cpp
This is update of czech translation for the new menu.
P.S. New menu looks great.
=> Updated czech translation

workspace/TS100/src/Translation.cpp
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** 
Strings translated in italian language
=> Update italian translation.cpp

workspace/TS100/src/Translation.cpp
Updated translation for Bulgarian with the latest version of Translation.cpp
Update of translations with a Bulgarian language
No Bulgarian translate is present
Ability to build firmware with Bulgarian translation
=> Bulgarian translation update

workspace/TS100/src/Translation.cpp
File revised and reformatted + fixed French language translation (#247)
=> Translation.cpp revised and reformatted

workspace/TS100/src/Translation.cpp
=> Spanish translation updated

workspace/TS100/build.sh
Localization added to https://github.com/Ralim/ts100/pull/262/commits/5fd5218d022774f1ba22735faf940e256138581a
=> Ukrainian language

workspace/TS100/src/Translation.cpp
Fixed some inaccuracies detected when viewing on the device.
=> Minor corrections of Russian localization

workspace/TS100/src/Translation.cpp
Changes in russian localization (typos, improvements, machine translation replacements). I'd like to maintain this in the future.
=> Additional changes in russian localization

workspace/TS100/inc/OLED.hpp, workspace/TS100/src/OLED.cpp
This is another one of a series of PRs that should help for #273 - introducing small changes to the codebase that attempt to reduce code size when using modern GCC compiler versions.
As per #273 - not all localisations can be built on GCC 6.3.1 and later.
The code is ~330 bytes smaller, which is at least 50% of the code overhead that prevents the Ukrainian locale build from compiling.
No.
=> Shrink OLED driver code.

workspace/TS100/src/Translation.cpp
=> added dutch translation

workspace/TS100/src/main.cpp
Silence compiler warnings for accelerometers variables being potentially uninitialised before usage.
Bug Fix.
The compiler complains about some variables potentially being unitialised before usage.
The compiler stops complaining.
No.
=> Initialise variables before usage.

workspace/TS100/src/Translation.cpp
Add Swedish translation
Additional language.
Swedish translation is missing
Swedish translation present
No.
=> Add Swedish translation

workspace/TS100/src/Translation.cpp
Updates Lithuanian translation
Lithuanian translation is out of date
Lithuanian translation is up-to-date
No
=> Update Lithuanian translation

Translation Editor/translation_en.json, workspace/TS100/src/Translation.cpp
Before: Are you sure to reset...
After: Are you sure you want to reset...
=> added missing verb to english translation

Translation Editor/translation_es.json, workspace/TS100/src/Translation.cpp
I've verified compilation and string lengths using the new editor.
I have *not* run this, mine should arrive tomorrow.
I'm not currently fluent in Spanish but I lived in Argentina for a couple of years when I was a kid.
=> updated spanish translation

Translation Editor/make_translation.py, Translation Editor/translation_bg.json, Translation Editor/translation_cs_cz.json, Translation Editor/translation_de.json, Translation Editor/translation_dk.json, Translation Editor/translation_en.json, Translation Editor/translation_es.json, Translation Editor/translation_fi.json, Translation Editor/translation_fr.json, Translation Editor/translation_hr.json, Translation Editor/translation_hu.json, Translation Editor/translation_it.json, Translation Editor/translation_lt.json, Translation Editor/translation_nl.json, Translation Editor/translation_no.json, Translation Editor/translation_pl.json, Translation Editor/translation_pt.json, Translation Editor/translation_ru.json, Translation Editor/translation_sk.json, Translation Editor/translation_sr.json, Translation Editor/translation_sv.json, Translation Editor/translation_tr.json, Translation Editor/translation_ua.json, Translation Editor/translations_def.js, workspace/TS100/src/Translation.cpp
Fix translations: add three new missing options
Translations have been added manually to `Translations.cpp` file which should not be done as it makes translation source files out of sync.
Translations are available through translations infrastructure and `Translations.cpp` is regenerated for all languages using `make_translation.py` script.
No
Supercedes https://github.com/Ralim/ts100/pull/363 by merging it into this branch.
=> Fix translations: add three new missing options

Translation Editor/translation_hu.json, workspace/TS100/src/Translation.cpp
Updated Hungarian translation
Some strings were missing, some could be improved
Added missing strings and fixed some old ones
No
=> Added new Hungarian strings and fixed some old ones

README.md
#377 occurred because we don't mention a potential issue with the instructions...
=> #377 - update install instructions to mention teracopy

Translation Editor/translation_ru.json, workspace/TS100/src/Translation.cpp
Updating the translations, keeping the files in sync
The translation.cpp and the json files are not in sync. Some translations are only in the json
The files are in sync. I used the latest available translations
No.
Somebody should update Translation.md to document the current process how to update / add a translation.
I will create a new issue for this.
=> Keep Translation.cpp and json-files in sync

Translation Editor/translation_ru.json, workspace/TS100/src/Translation.cpp
Keeping these files in sync seems to be an issue...
=> update russian json file, re-build Translation.cpp

workspace/TS100/build.sh
=> update Translation.cpp before build

workspace/TS100/.cproject, workspace/TS100/inc/hardware.h, workspace/TS100/src/main.cpp
Also add a #define used by sw4stm32/atollic so that the gui successfully builds.
=> remove hardcoded MODEL_TS80

Translation Editor/translation_fr.json, workspace/TS100/src/Translation.cpp
=> French translation improvements

workspace/TS100/src/gui.cpp, workspace/TS100/src/main.cpp
- [x ] The commit message make sense
Bug fix
https://github.com/Ralim/ts100/issues/427
No
=> Rotation fix

Translation Editor/translation_pt.json
- x ] The commit message make sense
=> Updated portuguese translation. All fields are now translated.

workspace/TS100/src/Translation.cpp
=> Minor changes _IT

Translation Editor/translation_it.json
Yeah, sorry about that.
---
Instructions in the wiki needs to be updated
=> [FIX] italian.json

Bootup Logo/python_logo_converter/img2ts100.py
- [NA] New features have been documented in the Wiki
Code cleanup
Passing a filehandle into a procedure so `.write` can be called many times on individual parts of the output
Turns that procedure into a generator function and calls `.write` once per call of `intel_hex_line` - but it can be easily changed to call it as many times as it did previously if there's a reason for that (low host memory?)
* **Does …
=> Make intel_hex_line a generator instead of passing in filehandle

workspace/TS100/Makefile
Space optimization, it saves about 1.6KiB of flash by using newlib-nano instead of newlib.
No
=> Use --specs=nano.specs to enable newlib-nano

Translation Editor/translation_sl.json
Adding Slovenian language (translation_sl.json) into Translation Editor.
=> Slovenian Translation

Translation Editor/translation_tr.json
- [*] The commit message make sense
- [*] I'm willing to maintain this in the future (Totally Optional)
Added turkish translations
=> added some turkish translations

workspace/TS100/Core/Inc/OLED.hpp, workspace/TS100/Core/Src/GUIThread.cpp, workspace/TS100/Core/Src/OLED.cpp
Made the display on/off mechanism a bit more self-descriptive by replacing bare true/false values with an enum with more appropriate value names.
OLED automatic turn-off logic has been cleaned up, along with minor updates to the OLED initialisation sequence.
The OLED display state management code could have been cleaned up a little.
N/A
Not really, the code has been refactored to maintain the same user-facing behaviour.
=> Refactor OLED on/off mechanism.

workspace/TS100/Core/Src/OLED.cpp
Changes the number printing to suppress leading zeros
`000123`
`   123`
#517
=> Walk over number prints to drop leader zeros

workspace/TS100/Core/Src/GUIThread.cpp, workspace/TS100/Core/Src/gui.cpp
This adds a 30 second timeout to the menu code, so that entering the menu and walking away wont leave the screen on forever.
#293 
Menu now times out after 30 seconds of no button presses and will drop the user back at the main screen
=> Menu should timeout

workspace/TS100/Core/Inc/OLED.hpp, workspace/TS100/Core/Src/GUIThread.cpp, workspace/TS100/Core/Src/OLED.cpp
Tweak to use nicer temp symbols in soldering mode
Fixes #438
=> Fix temp symbol

workspace/TS100/Core/Inc/OLED.hpp, workspace/TS100/Core/Src/OLED.cpp, workspace/TS100/Core/Src/gui.cpp
Small tweak to no zero suppress in two locations.
=> Fix dropped zeros

workspace/TS100/Core/Src/hardware.cpp
Drop inline on QC as not required
=> Drop inline on QC as not required

workspace/TS100/Core/Src/GUIThread.cpp
Replaces 'V' with SymbolVolts
Uses 'V' instead of SymbolVolts
=> Use SymbolVolts instead of V

Translation Editor/translation_en.json
AutoStard desc letters were not correct, I corrected these based on the characters and also fixed some spacing
Fixes a description typo and corrects the letters
=> Correct AutoStart desc

Translation Editor/translation_es.json
Added new strings, tweaked some existing and translated some un-translated strings
Added missing strings and tweaked/translated new/existing strings.
=> Updated es translation with new strings

workspace/TS100/Core/Src/GUIThread.cpp
Fix for https://github.com/Ralim/ts100/issues/571
Fix for https://github.com/Ralim/ts100/issues/571
Fix for https://github.com/Ralim/ts100/issues/571
No
=> Fix autostart S

workspace/TS100/Core/Src/GUIThread.cpp
Fix for https://github.com/Ralim/ts100/issues/569
https://github.com/Ralim/ts100/issues/569
https://github.com/Ralim/ts100/issues/569
No
=> Fix version screen for autostart T/S

Translation Editor/translation_bg.json, Translation Editor/translation_cs.json, Translation Editor/translation_da.json, Translation Editor/translation_de.json, Translation Editor/translation_en.json, Translation Editor/translation_es.json, Translation Editor/translation_fi.json, Translation Editor/translation_fr.json, Translation Editor/translation_hr.json, Translation Editor/translation_hu.json, Translation Editor/translation_it.json, Translation Editor/translation_lt.json, Translation Editor/translation_nl.json, Translation Editor/translation_nl_be.json, Translation Editor/translation_no.json, Translation Editor/translation_pl.json, Translation Editor/translation_pt.json, Translation Editor/translation_ru.json, Translation Editor/translation_sk.json, Translation Editor/translation_sl.json, Translation Editor/translation_sr_cyrl.json, Translation Editor/translation_sr_latn.json, Translation Editor/translation_sv.json, Translation Editor/translation_tr.json, Translation Editor/translation_uk.json, Translation Editor/translations_def.js, workspace/TS100/Core/Inc/Translation.h, workspace/TS100/Core/Src/GUIThread.cpp, workspace/TS100/Core/Src/gui.cpp, workspace/TS100/Core/Src/main.cpp
Fix for https://github.com/Ralim/ts100/issues/571
Fix for https://github.com/Ralim/ts100/issues/571
Fix for https://github.com/Ralim/ts100/issues/571
=> Fix autostart sleep (again)

Translation Editor/translation_es.json
Fix a few typos and awkward phrasing by non-natives. Adjust wording to meet the tight space limitations without losing information. Should be good to go.
Translation update with several improvements.
I sure hope not.
Thanks for the clever Web editor tool. I love the philosophy behind these tiny offline pages. I can see that a lot of thought went into the infrastructure.
I haven't made a custom build yet to test, but in general the strings are shorter than in the current one. I have gone through it and tweaked words here and there in various passes until everything fell into place, so hopefully this improves …
=> Update and proofread the Castilian Spanish translation file

workspace/TS100/Core/Src/OLED.cpp, workspace/TS100/configuration.h
=>  PR#5- bool inLeftHandedMode is an internal variable. Reverting configuration.h assignment

Translation Editor/translation_en.json
* Update translation_en.json
The meaning for the 'O parameter' in the scrolling description was missing.
* Update translation_en.json
Proposal for consistent appearance of text.
(What changes might users need to make in their application due to this …
=> hopefully consistent appearance

workspace/TS100/Core/Src/main.cpp
Simplifies logo presence check, by using a simple 32 bits comparison rather than four 8 bits comparisons. 
Behaviour stays the same on my TS100 iron.
=> Simplify logo presence check.

Dockerfile, docker-compose.yml
Bumping compiler up as preventative measure.
=> Update to newest compiler from ARM

workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/croutine.c, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/FreeRTOS.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/atomic.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/croutine.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/deprecated_definitions.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/event_groups.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/list.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/message_buffer.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/mpu_prototypes.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/mpu_wrappers.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/portable.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/projdefs.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/queue.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/semphr.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/stack_macros.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/stream_buffer.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/task.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/include/timers.h, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/list.c, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/queue.c, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/tasks.c, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/timers.c
Updating FreeRTOS kernel to latest
=> Update FreeRTOS to v10.3.1

README.md, menu.md, upgrading.md
Creating a new flashing guide doc with a tiny FAQ.
Re-restructuring the files to be more divided by topic.
=> Updating some of the markdown docs

Translation Editor/translation_cs.json
Only translation update.
The changes have been tested locally
=> Translated remaining CS (czech) strings

upgrading.md
- [-] Are there any breaking changes
Docs update.
=> New TS100 v2.51A version allows SWD over USB pins

Translation Editor/translation_it.json
**Please check if the PR fulfills these requirements**
**Other information**:
=> IT_translation update

Translation Editor/translation_es.json
I see that a lot of things have changed lately. Time for a Castilian Spanish translation update. Great work. :)
=> Update the Spanish translation to cover the recent UI changes

workspace/TS100/Core/BSP/Miniware/Setup.c, workspace/TS100/Core/BSP/Miniware/flash.c, workspace/TS100/Core/BSP/Miniware/logo.cpp, workspace/TS100/Core/BSP/Miniware/postRTOS.cpp, workspace/TS100/Core/BSP/Miniware/system_stm32f1xx.c, workspace/TS100/Core/Src/Settings.cpp, workspace/TS100/Core/Src/main.cpp, workspace/TS100/LinkerScript.ld, workspace/TS100/Makefile, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/port.c, workspace/TS100/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/portmacro.h
Hello,
This is not a feature branch, just some improvements (hopefully) I made while playing with your firmware. Please cherry-pick as you see fit or advice me how to proceed (I can create a separate "github pull-request" per patch if you want me to).
I would also like to discuss with you the idea of using LOCAL_BUILD for running firmware without a bootloader. My impression is that having a bootloader is always good, as one can connect via SWD without disassembly and messing with the RESET or BOOT0 pins, and it still allows debugging the firmware itself. What would be the best medium to discuss it, should I create an "issue" for that?
BTW, 128k flash is available when starting OpenOCD with ``-c 'set FLASH_SIZE 131072' `` before ``-f target/stm32f1x.cfg``, I guess I should have mentioned …
=> RFC patches

.github/workflows/ccpp.yml
This moves the artefact uploads to be per-model for ease :)
=> Move artefact outputs to be done per model

.github/workflows/ccpp.yml, Dockerfile, setup.sh, workspace/TS100/build.sh
More CI performance increase
* Runs all builds in parallel
* Avoids using the extra docker container in CI
=> CI performance

workspace/TS100/Core/Inc/gui.hpp, workspace/TS100/Core/Src/gui.cpp, workspace/TS100/configuration.h
PoC code, just "boost temp" and "temp change short" implemented.
Probably fixes #536.
I have no idea why state_func needs to be a struct.
=> [RFC] add a pause for the last value in settings menus

Translation Editor/translation_it.json
Text formatting and small improvements
=> Small adjustments in IT_translation

workspace/TS100/Core/Threads/MOVThread.cpp
Fix for https://github.com/Ralim/ts100/issues/696
=> Delay accelerometer for 2 seconds - fix for #696

README.md
Fixes a couple of typos that were creating broken links in the README file
=> Fix a couple of typos creating bad links in the README file

Translation Editor/translation_nl.json
I've updated some of the dutch translations.
Some were not yet in dutch and others were incorrect/incomplete translations
=> Updated dutch translations

Translation Editor/translation_it.json
=> New IT translation

Translation Editor/translation_lt.json
Update translation using TranslationEditor
=> translation_lt.json

Translation Editor/translation_de.json
German Translation improvement
N/A
N/A
N/A
=> Improved German translation

workspace/TS100/Core/Threads/GUIThread.cpp
Blink speed of the cool down blink is super fast
https://github.com/Ralim/IronOS/issues/765
Slowed down the blink speed a bit
=> Fixed the blinking speed of cool down blink

Translation Editor/translation_it.json
Adjustments in the Italian translation
=> New strings - IT translation

Translation Editor/translation_sl.json, setup.sh
- [*] The changes have been tested locally
- [*] There are no breaking changes
Fully translated firmware into Slovenian language
Changes were tested on my own Pinecil
=> Updated translation_sl.json

Translation Editor/translation_pl.json
=> Better PowerPulsePower translation

Translation Editor/translation_hu.json
Update and minor fix to the Hungarian translation.
tranlation update
=> Update Hungarian translation

Translations/translation_sk.json
Incomplete, substandard, misleading translation
=> Update Slovak translation

Translations/translation_sk.json
=> Slovak translation typo fix

.github/workflows/push.yml, Dockerfile, LICENSE_RELEASE.md, Translations/README.md, Translations/make_translation.py, Translations/translation_YUE_HK.json, Translations/translation_ZH_TW.json, Translations/wqy-bitmapsong/AUTHORS, Translations/wqy-bitmapsong/COPYING, Translations/wqy-bitmapsong/README.md, Translations/wqy-bitmapsong/README_original, setup.sh, source/Core/Drivers/OLED.cpp, source/Core/Src/gui.cpp, source/Core/Threads/GUIThread.cpp, source/Makefile
Feature
Initial support for CJK translations with Chinese (Taiwan, Traditional) and Cantonese (Hong Kong) translations included.
Closes #791
Note: This PR includes a commit from #844
=> CJK support with zh-TW and yue-HK translations

Translations/translation_DE.json
Minor changes to the German translation:
- Fixed two typos
- Shortened some menu descriptions. (One was so long that the iron returned to the main view before the entire description text scrolled through.)
=> Update German translation

Translations/translation_BG.json, Translations/translation_CS.json, Translations/translation_DA.json, Translations/translation_DE.json, Translations/translation_EN.json, Translations/translation_ES.json, Translations/translation_FI.json, Translations/translation_FR.json, Translations/translation_HR.json, Translations/translation_HU.json, Translations/translation_IT.json, Translations/translation_LT.json, Translations/translation_NL.json, Translations/translation_NL_BE.json, Translations/translation_NO.json, Translations/translation_PT.json, Translations/translation_SK.json, Translations/translation_SL.json, Translations/translation_SR_CYRL.json, Translations/translation_SR_LATN.json, Translations/translation_SV.json, Translations/translation_TR.json, Translations/translation_YUE_HK.json, Translations/translation_ZH_TW.json
=> Forgot to add desc. to MinVolCell

source/Core/Src/gui.cpp
Fix scroll speed error with `userConfirmation` introduced in #874
`userConfirmation ` scrolls too slowly.
=> Fix userConfirmation scroll speed

Translations/translation_YUE_HK.json, Translations/translation_ZH_TW.json
Update translations.
I had to remove some characters in the yue-HK translation, but still in this update it has used up all the available symbols slots. This is going to be a problem when more strings are added in the future.
=> Update yue_hk and zh_tw translations

Translations/translation_IT.json
=> Updates in italian translation

Translations/make_translation.py, Translations/make_translation_test.py, source/Core/Drivers/OLED.cpp, source/Core/Src/gui.cpp
=> Extend font encoding changes

Translations/make_translation.py
Refactoring
Move all CJK symbols to the end of the font table so we can skip the filler for the CJK symbols in the small font table to save some space.
It saved 1112 bytes for yue_hk. I've checked and don't see any size regressions for non-CJK builds, but curiously some builds also have a 8-byte decrease...
I think the new code is also slightly clearer but this is subjective.
=> Reorganize font table of CJK languages

.github/workflows/codeql-analysis.yml
Speeding up the codeql analysis.
=> Use cache for codeql

source/Makefile, source/Middlewares/Third_Party/FreeRTOS/Source/tasks.c
This improves the out-of-the-box debugging experience, please see the commit messages for more detailed explanations.
=> Improve debugging

Translations/translation_PL.json
=> Update PL translation

Translations/translation_ZH_CN.json, source/Makefile
- ✔️  The changes have been tested locally
- ✔️  There are no breaking changes
Add translation for Chinese (Simplified)
=> Add ZH_CN translation

Translations/translation_IT.json
=> Small update in italian translation

Translations/translation_JA_JP.json, source/Makefile
- ✔️  The changes have been tested locally
- ✔️  There are no breaking changes
Add translation for Japanese
~~I actually don't really know Japanese (I can read a limited amount but that's it). I was bored and wanted to see how a Japanese UI would look like. I did the translations based on Google Translate and online dictionaries. I think this should be at least readable but the quality is unknown.~~
~~I am making this public in the hopes that some native Japanese users can improve upon this without needing to start from scratch, but I am not sure if this should be merged as-is.~~
Reviewed and amended by @skishida.
=> Add Japanese translation

Translations/translation_ES.json
Update of the Spanish translations, some messages were still in English
=> update of Spanish translations

Documentation/Menu.md
Docs update
(Took me longer then I want to admit I simply had to press them, not hold them... Felt like a buffoon :smile: )
=> [Docs] Fix how to exit VIN calib

Translations/translation_SV.json
-  [x] The changes have been tested locally
-  [x] There are no breaking changes
Language fixes
Some fields are the wrong size, some are not translated
I did the original translation, and it hasn't been updated in a 2 years (sorry about that).
=> Add missing SV translations and fix errors

.github/workflows/push.yml, source/Core/BSP/MHP30/Vendor/STM32F1xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h, source/Core/BSP/MHP30/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_dma_ex.h, source/Core/BSP/MHP30/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_gpio_ex.h, source/Core/BSP/MHP30/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_i2c.h, source/Core/BSP/MHP30/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_tim.h, source/Core/BSP/Miniware/Vendor/STM32F1xx_HAL_Driver/Inc/Legacy/stm32_hal_legacy.h, source/Core/BSP/Miniware/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_dma_ex.h, source/Core/BSP/Miniware/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_i2c.h, source/Core/BSP/Miniware/Vendor/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_tim.h
Attempt 2 to bring back clang format
=> Fix ci formatter

Translations/translation_JA_JP.json
- Add some missing translations
- Fix incorrect translations
=> Update JP translation

Translations/translation_SK.json
Just translated a few more words in SK translation and made some changes, although, I left some words not translated since I wasn't fully sure how to name them in my language 😀 so hopefully someone else will pick them up,
NOTE: I just noticed that my translation file have different tab size and also format, I was editing the JSON via the `TranslationEditor.html`, so I guessed it supposed to be like this
=> Update SK translation

Translations/translation_IT.json
This pull request is intended to replace #1068 (I really don't know other way to propose factual changes to other's pull requests in Github).
I followed some valid indication, however a few of the sentences needed a change.
The code is taken directly from the builder.
=> Updates in IT translation

Translations/translation_YUE_HK.json, Translations/translation_ZH_CN.json, Translations/translation_ZH_TW.json
Translation update (zh_TW, zh_CN, yue_HK)
=> Update Chinese translations

source/Core/Src/Settings.cpp, source/Core/Src/gui.cpp
=> change increment and values of brightness settings

Translations/translation_IT.json
Just some improvements in the translation.
It's good to go.
Sorry for taking me more than one PR every time.
=> IT translation - second update

Translations/translation_BE.json, Translations/translation_BY.json
add new language (Belarussian)
=> add new language (Belarussian)

Translations/translation_YUE_HK.json, Translations/translation_ZH_TW.json
Had some inspirations after seeing #1127.
=> Some improvements for Traditional Chinese and Cantonese

Translations/translation_ZH_CN.json
Some Simplified Chinese translations were improved to be more in line with the vernacular.
=> Improve Simplified Chinese translations

source/Core/Src/Settings.cpp
=> changed POWER_PULSE since 100 would display as 0.0

Translations/translation_RU.json
Updated translation of the PD section
=> Updated translation of the PD section

source/Core/Src/Settings.cpp, source/Core/Src/gui.cpp
Fixing scroll indicator to update correctly when menus turn on and off, and also position correctly.
https://github.com/Ralim/IronOS/issues/1139
=> Handle menu sizing better

.github/ISSUE_TEMPLATE/bug_report.md
typo and formatting fix
makes my eye twitch
still annoys me at the use of "behavior" instead of "behaviour"
=> bug_report.md: minor cleanup

.github/workflows/shellcheck.yml
Adding shellcheck as a CI step as a spin out from #1144
=> Adding Shellcheck to CI

README.md
=> updated some entries

Translations/translation_HU.json
translation update, extra comma removed
=> Hungarian translateion update v2

source/Core/Drivers/OLED.hpp, source/Core/Threads/GUIThread.cpp
Just cleaning up some OLED logic to be a bit cleaner
=> Cleanup OLED_FLIP logic

source/Core/Threads/GUIThread.cpp
@discip 
This should fix the soldering mode _correctly_
=> Fix lefty mode again

.github/workflows/push.yml, Dockerfile
Moving the last parts of CI over to alpine, to make it simpler for reproducibility
=> Format to alpine

.github/workflows/push.yml, source/metadata.py
Closes #1217 by generating an index for each file and attaching to the release
CI will build an index file with the same name for tools to use.
=> Create json meta

Translations/BitmapEditor.html
Original updates started by @ Pikapoo on the Pinecil community chat
Further improvements and png work by Robert Lipe <robertlipe@gmail.com>
I wrote _none_ of this, I deserve no credit :)
=> Enhanced to have PNG download and scaling

Documentation/Flashing.md
Covers an issue where more than one DFU interface is detected.
=> Update Pincecil flashing instructions

Documentation/Troubleshooting.md
Trying to start a reference list for help troubleshooting hardware issues.
=> Starting troubleshooting list

Translations/translation_HU.json
=> Fix translation_HU.json

Documentation/Flashing.md
- Added Info to Troubleshooting section
- fixed broken links, and minor edits.
=> Updated Flashing doc

Documentation/Flashing.md
Change the offered alternative bootloader to Ralim's one. This one also works on other devices, not only TS100.
=> Update docs with new Miniware DFU bootloader

Bootup Logo/README.md
fixed incorrectly formatted file link in readme
=> Minor Bootup Logo readme fix

Documentation/DebugMenu.md, Documentation/Development.md, Documentation/Flashing.md, Documentation/Hardware.md, Documentation/HardwareIssues.md, Documentation/Logo.md, Documentation/Menu.md, Documentation/Power.md, Documentation/Troubleshooting.md
I have tried to fix some typos and enhance the documentation, feel free to leave feedback.
=> Typo fixes and various improvements

Translations/translation_PL.json
=> Update PL translation (v2.18)

Translations/translation_CS.json
Reflect the newest firmware changes
=> Update Czech translation

.github/workflows/push.yml, Dockerfile, source/Core/BSP/BSP.h, source/Core/BSP/MHP30/BSP.cpp, source/Core/BSP/MHP30/ThermoModel.cpp, source/Core/BSP/Miniware/BSP.cpp, source/Core/BSP/Pine64/BSP.cpp, source/Core/BSP/Pine64/configuration.h, source/Core/Threads/GUIThread.cpp, source/Core/Threads/PIDThread.cpp
* Bug fix for #1294
* Revert PPS 21V limit as it makes some PSU's unstable
* Bumps to newer alpine image
* Bit of a cleanup of how we handle "startup tasks" so its less hacky
=> Startup behaviour fixes

README.md
Trying to add a summary table of features supported across models
=> Adding features table

source/Core/Drivers/BootLogo.cpp
solves https://github.com/Ralim/IronOS-Meta/issues/18
=> solves artifacts issue if .gif is exactly 1024 B

source/Core/BSP/MHP30/configuration.h
Add SC7 accelerometer for MHP30
=> Add SC7 accelerometer for MHP30

Translations/translation_BE.json, Translations/translation_PL.json, Translations/translation_RU.json, Translations/translation_UK.json
Update translations for UK, RU, BE
=> update translation_UK.json translation_RU.json translation_BE.json translation_PL.json

Documentation/Menu.md
=> solving issue #1423

Translations/font_tables.py, Translations/make_translation.py, Translations/translation_EN.json
Trying to cleanup translations files to do some refactoring of translations
=> Cleaning up translations a small amount

Translations/translation_IT.json
=> Revision on IT translation

source/Core/Threads/OperatingModes/HomeScreen.cpp
=> fixes cooldown flashing

Translations/translations_definitions.json
=> Just a small typo correction and a suggestion for clearer wording.

Translations/translation_EN.json
=> minor formatting fix

Translations/translation_DE.json
=> Updated translation_DE.json

source/Core/BSP/Pinecilv2/ble_handlers.cpp
Implements #1610 
- [+] The changes have been tested locally
- [+] There are no breaking changes
=> Add FW version to BLE characteristic

source/Core/BSP/MHP30/configuration.h, source/Core/BSP/Miniware/configuration.h, source/Core/BSP/Pinecil/configuration.h
=> adapting 10 °C > 50 °F

source/Core/BSP/Pinecilv2/configuration.h
as discussed here:
https://github.com/Ralim/IronOS/pull/1641#issuecomment-1494917367
&
https://github.com/Ralim/IronOS/pull/1641#issuecomment-1500663620
=> correcting MAX_POWER_LIMIT to 120

source/Core/Src/settingsGUI.cpp
=> corrected character count

source/Core/Src/settingsGUI.cpp
@codingcatgirl
Please have a look, I may have missed something here.
=> removing extra entries

Translations/translation_DE.json
=> corrected wording

source/Core/BSP/Pinecilv2/Setup.cpp, source/Core/BSP/Pinecilv2/bl_mcu_sdk/common/misc/compiler/common.h, source/Core/BSP/Pinecilv2/bl_mcu_sdk/drivers/bl702_driver/bl702_flash.ld, source/Makefile
This is to try and reduce BLE issues.
I cant reproduce the BLE issues; so making this for others to test.
@River-Mochi If you are able to test this would be epic?
=> Adjust how heap and ram sections are allocated

Translations/translation_IT.json
I have corrected some expressions. 
Ready to be merged, thanks.
=> Translation_IT.json rev.2

Translations/translation_RU.json, Translations/translation_UK.json
Fixed mismatch between letters and descriptions in UK and RU translations
=> Merging newest translations into dev

source/Core/Inc/Settings.h, source/Core/Src/settingsGUI.cpp, source/Core/Threads/OperatingModes/Sleep.cpp
I was trying to implement one tiny feature (unsuccessfully). But ended up with this tiny `AutoStartMode` values refactoring. If you think that it can be useful for code readability, then I will be happy to see it merged. I picked the constants' names to reflect the temperature for autostart mode.
=> AutoStartMode refactoring

Translations/translation_ES.json
- [Y] The changes have been tested locally
- [Y] There are no breaking changes
Spanish translation is complete  and previous attempts have been reworded to the correct translation
Some pairs were left untranslated (i presume due to new features) and displayed english text, other were worded very wrong
Full translation and correct meanings
https://github.com/Ralim/IronOS/issues/1714
=> Spanish translation is 100% complete

Translations/translation_DE.json, Translations/translation_EN.json, Translations/translation_NL_BE.json, Translations/translation_SR_CYRL.json, Translations/translation_SR_LATN.json
For details see #1673.
closes #1673
=> correct wording for 'max power'

source/Makefile
Tiny help with formatting, nothing else.
Just a small suggestion to merge in your branch before it will be merged back to `dev`.
=> Unify formatting for changes in source/Makefile

Translations/translation_SV.json
\* *Only translation JSON strings have been edited.*
Translation update for Swedish language. 
English strings are used in place of the strings that have yet to recieve a Swedish translation. 
All strings are now translated into Swedish.
This has not been tested on device as I don't have access to one. Longer words may need shortening. I tried my best to keep things short so to not run off the screen.
=> Swedish translation update to include new strings

Translations/translation_BG.json
Update translation for Bulgarian language.
Some of text lines are not translated in Bulgarian.
Translate & update text lines in Bulgarian.
I made all model builds with BG locally successfully but I could verify on a real device only those translated lines which are valid for `TS80P`. Where the lines were too long, we tried to use common "shortenings".
Huge thanks for big help goes to ❤️ Iliana.
=> Update & translate for Bulgarian language

Translations/translation_RU.json
Update translation for Russian language.
Some of text lines are not translated in Russian.
Translate & update text lines in Russian.
I made all model builds with RU locally successfully but I could verify on a real device only those translated lines which are valid for `TS80P`. Where the lines were too long, we tried to use common "shortenings".
Huge thanks for big help goes to ❤️ Iliana.
=> Update & translate for Russian language

Documentation/HardwareIssues.md, Documentation/Troubleshooting.md
Add OLED model info & replacement recommendation into Documentation.
There is no detailed info about OLED although in some models it's relatively easy replaceable.
Update ~`HardwareIssues.md`~ `Troubleshooting` document with additional section addressing OLED model info, its replacement & recommendations.
[During scouting](https://github.com/Ralim/IronOS/discussions/1751) the opened issues, I saw more than one mention about dead OLED. Since there is a separate document dedicated to hardware issues already anyway, I think that info about OLED model ~& its …
=> Add detailed OLED replacement info to `Troubleshooting` document

Translations/translation_ZH_CN.json, Translations/translation_ZH_TW.json
Translation update.
Some newer strings are not translated to Chinese.
Translated to Chinese.
I'm not very good at zh_TW so some of the terms might sound strange.
=> Add missing Chinese translation

Documentation/Flashing/MHP30.md, Documentation/Flashing/TS100.md, Documentation/Flashing/TS80(P).md, Documentation/Hardware.md
Documentation update.
Documentation points to external but decommissioned wiki.
- references updated to related sections inside actual documentation;
- links added to backups of original firmware from the supplementary repo.
Changes have been tested using [forked instance](https://ia.github.io/IronOSf) with Read-the-Docs to make sure that formatting didn't break. [Anchor refs are working as well](https://ia.github.io/IronOSf/Flashing/MHP30/#linux).
=> Updating references in the docs

Translations/translation_ET.json
Additional language.
Estonian translation is missing
Estonian translation present
=> Add Estonian translation

Translations/translation_SK.json
=> Fix typo in SK translation for `ProfilePhase5Duration`

Documentation/PortingToNewDevice.md
=> Add rough pass on porting support

Translations/translation_UK.json
Translate PD options to Ukrainian
=> Update translation_UK.json with PD mode option

Translations/translation_RU.json
Update RU translation for PD mode options.
Description for PD mode and its modes are not translated.
Translated description for PD mode and for its modes.
Before submitting the patch I did make a set of custom builds to find the most adequate _"adoption"_ to make it fit and to have it clear (as much as possible) at the same time for an average user.
=> Update RU translation for PD mode options

Translations/translation_IT.json
=> PD modes IT translation

Translations/translation_BG.json, Translations/translation_RU.json
Update RU translation for PD mode options.
Description for PD mode and its modes are not translated.
Translated description for PD mode and for its modes.
Before submitting the patch I did make a set of custom builds to find the most adequate _"adoption"_ to make it fit and to have it clear (as much as possible) at the same time for an average user.
Also, I tried to get some additional information about options and what exactly they do [here in a form of code review comment](https://github.com/Ralim/IronOS/pull/1917). But I think I figured it out after all, more …
=> Update BG translation for PD mode options

Translations/translation_IT.json
=> Small fix IT language

Translations/make_translation.py
=> changed date format to YYYY-MM-DD

Translations/make_translation.py
=> YY-MM-DD => YYYY-MM-DD

source/Core/BSP/Miniware/configuration.h, source/Core/Drivers/LIS2DH12.cpp
Trying to fix #1849 without breaking TS101
#1849
=> Mask LIS2DH12 clone support for TS101 only

source/Core/BSP/MHP30/stm32f1xx_hal_msp.c
* **What is the current behaviour?**
Closes #1986
* **What is the new behaviour (if this is a feature change)?**
Closes #1986
=> Change Input mode of the tip sense signal for Miniware

Documentation/History.md
Add info about _v2.22_ to `History.md`.
_v2.22_ release info is missing from `History.md`.
Info about _v2.22_ being added to `History.md`. Also, titles and subtitles are unified according to markdown headline syntax.
While I was adding the link to `History.md` aka changelog in `README.md` and checking it, I noticed that we were so busy that forgot to add current release info to `History.md`.
P.S. I think I may have some thoughts about automagically check for this, in the near future. ;)
=> Add info about v2.22 to History.md

README.md
Fix mistypes in `README.md` introduced by previous update (#1991).
Mistypes in `README.md` discovered & pointed out by @yo3fxy in the review for the previous update.
Fixed mistypes.
Could you, @yo3fxy, please, to double check again any possible mistypes here in case we still did miss something? Thank you for your code review feedback, good catch, really.
=> README.md: fix mistypes discovered by @yo3fxy

Translations/translation_IT.json
=> IT translation update

Translations/translation_ZH_CN.json
ZH_CN translation update
[Pinecil V1 small display error in ZH_CN](https://github.com/Ralim/IronOS/issues/1780)
It doesn't aim to fix the problem in the issue, just a translation update.
=> improve zh_cn translation

README.md
=> changed `Devel Build` => `Development Build`

README.md
Rename _"Devel builds"_ to _"Development Build"_ in the description from _Builds_ section of `README.md`.
Inconsistent terminology.
Unify terminology to avoid confusion and rearrange description section using markdown list.
Follow up for #2022.
=> README.md: reformat description section for build types to make it more consistent

Translations/translation_RU.json
Update RU translation.
Not all the lines are translated in `translation_RU.json`.
Updated `translation_RU.json`.
I honestly did test everything related as I could on my _TS80P_, and I think I may discovered minor issue, but since it's not related to the translation itself I will try to address that later at this week in a separate pull request/issue.
=> Update RU translation

source/version.h
Bumping version to enable tagging out the RC
=> Update version for RC-1

Documentation/Logo.md
Typo in `Documentation/Logo.md` corrected (Squire -> Sequre)
=> Typo corrected (Squire -> Sequre)

Translations/translation_DE.json
Added new line to translated "Soldering Tip Type" string
=> Updated translation_DE.json (again)

Translations/translation_PL.json
=> Update PL translation (v2.23 rc1)

source/Core/Threads/UI/logic/OperatingModes.h
Fix the OperatingModes struct to match the ID's of the older 2.22 release
Closes #2039 
=> Allocate fixed ID's for Operating Modes

source/Core/BSP/Pinecilv2/I2C_Wrapper.cpp, source/Core/Threads/UI/logic/utils/SolderingCommon.cpp
Not required, may fix some issues with latency of interrupts
=> Drop critical section on I2C

README.md
Fix mistypes from [my own previous PR](https://github.com/Ralim/IronOS/pull/2067) in `README.md` related to heading levels for BLE section.
Malformed heading levels in `README.md`.
Proper markdown-based heading levels in _Remote Control_ section of `README.md`.
Pardon me for being too rush and not checking edited headers properly. :/
Also highlighted "AS IS" as "highlight-able" as possible.
=> README.md: fix formatting of heading levels for BLE section

source/Core/Drivers/USBPD.cpp
Some laptops need this, so this just responds with a minimal answer to keep things happy.
This only adds basic profiles (no pps/epr) for now.
This will likely fix _some_ of the device reboots on X issues.
Probably doesnt fix _all_
=> USB-PD: Add minimal sink caps

Translations/translation_FR.json
Update of the translations and warning messages in the user interface, along with improved clarity of certain terms.
Translated new features that weren't translated yet.
The user interface messages use less precise terms and less optimized translations. Some text isn't even translated yet.
- Corrected several translation terms.
- Improved warning messages for better clarity, such as "LOW VOLTAGE" and "Tip Shorted".
- Updated text strings to better match their usage contexts in French, such as "Power Source" and "Default Mode".
- Most of the text is translated.
- …
=> Updated Overall French Translations

Translations/translations_definitions.json, source/Core/BSP/MHP30/stm32f1xx_hal_msp.c, source/Core/Drivers/OLED.cpp, source/Core/Threads/GUIThread.cpp
Closes #2036
Closes #2092
Closes #2043
Helps with #1739
Tested on my triplet of MHP30 units
=> Mhp 30 fixes

Documentation/README.md, Documentation/WS2812BModding.md, scripts/IronOS-mkdocs.yml, source/Core/BSP/Pinecilv2/BSP.cpp, source/Core/BSP/Pinecilv2/Pins.h, source/Core/BSP/Pinecilv2/preRTOS.cpp, source/Core/Drivers/WS2812B.h, source/Makefile, source/build.sh
It adds code to support modding a Pinecil V2 to add a WS2812B.
See https://github.com/Ralim/IronOS/issues/1739 for details.
All the code is protected by a define so it is virtually absent if the option is not used.
I added a page of documentation to explain how to use it.
Feel free to add commits as needed before merging.
Thank you.
=> Adding Pinecilv2 ws2812b mod option

Documentation/Logo.md
=> blisp typo in Logo.md

.github/workflows/push.yml, Documentation/Settings.md, Translations/gen_menu_docs.py, Translations/translations_definitions.json
Fixing up the documentation to ensure it stays in-sync
=> Fix docs gen check

scripts/flash_ts100_linux.sh, scripts/flash_ts10X_linux.sh
Feature update
Flashing script requires 2+ non-automated tries and seems to be only for TS100
Flashing script now automatically retries and has more generalized wording
Polished and uploaded a feature that I added for myself quite a while ago)
=> Updated flasher script with some quality of life

Documentation/index.md, source/Core/Threads/UI/logic/Soldering.cpp
* **Please check if the PR fulfils these requirements**
Bug fixes
* **What is the current behaviour?**
Fixes #2115 
Fixes #2131 
* **What is the new behaviour (if this is a feature change)?**
=> Fix 2115 2131
