python_logo_converter/img2ts100.py
For review, test, and possible inclusion in main repository.
This is a commandline-only utility: No GUI, no visual display, no interactive control. It depends on and requires installation of the Python Imaging Library (PIL). A semi-user-friendly error message with hints on how to do this is provided.
The code has been tested against one 96x16 1-bit colormap PNG input image and produces Intel hex output that is byte-identical (including DOS "\r\n" line endings) to a file created with the original C# TS100 Logo Editor utility.
It should do the same for any 96x16 pure black-and-white input image regardless of file format. It will not create byte-identical output for any other size or color/grayscale input as it uses a more standard grayscale-to-1bit conversion from the PIL. Any reasonably …
=> Python version of Logo Editor/TS100 Logo Editor

workspace/TS100/src/Translation.c
I really like the double line layout. This is an Update for the German translation.
I noticed that there doesn't seem to be unicode support in the smaller font. Are there any plans to add that in the future? It would be definitively nice to have that for this translation.
=> Update German translation to double lines in settings

workspace/TS100/inc/Translation.h, workspace/TS100/src/Translation.c
Merge first as I unified and corrected the formatting in the whole `Translation.c` file. Then merge other language related pull requests in unified formatting.
Quite a few languages has missing a comma between texts in array making the array wrongly initialized.
This pull request fixes that. I think the affected languages are mainly those ported from 1.x version. This problem was pointed out for Italian language in issue #159.
=> Fix menu descriptions (merge first)

workspace/TS100/src/Settings.cpp
According to the linker script the settings should go on the last
available page of the devices flash rom. This should be page 63
starting at 0x800fc00.
=> Changed starting address for saving the device settings in flash.

workspace/TS100/src/Translation.c, workspace/TS100/src/gui.cpp
This puts `Factory reset` as the last menu option as commonly used in device menus.
=> Menu factory reset last

workspace/TS100/inc/Translation.h, workspace/TS100/src/Translation.c, workspace/TS100/src/main.cpp
Externalized strings:
* "Undervoltage"
* "Input V: "
* "DC LOW" (Using previously unused ULOWarningString)
* "Tip Temp: " (At temperature warning)
* "Tip:" (At sleeping advanced)
* "Tip:" (At idle screen)
* " Set:" (At idle screen)
* "BAD TIP"
* "Tip Disconnected!" (changed to "TIP DISCONNECTED" due to <=16 limit)
Max string length corrected from 17 to 16. Translations in some languages should be reviewed/corrected accordingly.
Additionally, added double-line menus for Croatian Language, together with some minor translation corrections.
**NOTE:** Warnings strings might be better if displayed with all-caps, such as "UNDERVOLTAGE" etc. I didn't change that in English (it is up to you, if you find it appropriate), but I did that in Croatian.
=> Croatian Language: Double-line menus + some minor translation corrections

workspace/TS100/src/OLED.cpp
Do draw area also if just part of it is visible - e.g. do not skip whole letter in rolling description if half of it can be shown.
=> Adjust left limit for drawing

workspace/TS100/src/gui.cpp
Same as #184 - `Factory reset` should be the last menu option as commonly used in device menus.
=> Factory reset as last item (again)

workspace/TS100/inc/LIS2DH12.hpp, workspace/TS100/inc/MMA8652FC.hpp, workspace/TS100/inc/hardware.h, workspace/TS100/src/LIS2DH12.cpp, workspace/TS100/src/MMA8652FC.cpp, workspace/TS100/src/main.cpp
This is one of a series of PRs that should help for #273 - introducing small changes to the codebase that attempt to reduce code size when using modern GCC compiler versions.
As per #273 - not all localisations can be built on GCC 6.3.1 and later.
The code is ~150 bytes smaller, which is at least 25% of the code overhead that prevents the Ukrainian locale build from compiling.
No
=> Reduce code size for accelerometer support

workspace/TS100/Makefile
LTO can make a significant impact on flash space when using ST HAL drivers.
I've tested it on my iron, seems to work fine. Had a slight problem with interrupt vectors optimizing out, but solved it by reordering link order on line 194 
Before:
```
arm-none-eabi-size Hexfile/TS100_EN.elf
text	   data	    bss	    dec	    hex	filename
43992	   1760	  13400	  59152	   e710	Hexfile/TS100_EN.elf
```
after:
```
arm-none-eabi-size Hexfile/TS100_EN.elf
text	   data	    bss	    dec	    hex	filename
38896	   1460	  13408	  53764	   d204	Hexfile/TS100_EN.elf
```
With some more optimizations, it might be possible to fit a small usb stack with CDC. :)
Tools used:
`gcc version 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204] (GNU Tools for Arm Embedded Processors 7-2017-q4-majo`
=> Use LTO to save up to 7k of flash

workspace/TS100/Makefile
There's no way to generate the firmware in binary format using the Makefile. As a dapboot user (dapboot **only** takes binary, **not** intel hex ftw) I found out that this is really inconvenient so I decided to add binary file generation to the Makefile.
`make all` only generates the firmware in Intel HEX format (works for official DFU)
`make all` generates the firmware in Intel HEX format (works for …
=> Add binary generation to the Makefile

workspace/TS100/src/main.cpp
Display seconds until sleep in soldering mode.
For time > 99 seconds display minutes instead.
Note: it is a fairly trivial change and I can imagine the feature is not desired by everyone. I used it while playing with different motion sensivity settings and made a pull request just in case.
Feature
The user has no feedback as to when the unit will enter sleep mode
In the advanced settings next to the output power it will display the time left intil sleep.
No
I assumed S and M are internationally acceptable for …
=> Display seconds until sleep in soldering mode.

workspace/TS100/src/main.cpp
rawC should be positive. Previously the int32_t was being cast to a uint8_t. I'm surprised at how well it was working...
As a result, we had to change the mass divisor - rawC was ~2.5 times larger than it should have been, so we have to bump up the divisor by 2.5 times to have identical performance.
---------------
Also, if a very large set point was chosen, sometimes tempError overflowed - it's int16_t. Cap the values. Surprisingly, capping the error hasn't increased size at all! Good job, compiler.
=> Watt fixes

workspace/TS100/src/main.cpp, workspace/TS100/src/power.cpp
This reduces the watt calculations by ~20%.
Because our mass calculation was done before-hand, we need to counter this by boosting the mass by ~20%. `(1690 * ((255+50) / 255))`
This code hasn't been tested.
=> adjust watts for PWM duty cycle

workspace/TS100/build.sh
New script to generate all *.hex files
```
Usage : ./build.sh [-l <LANG_CODE>] [-m <TS100|TS80>] [-h]
Parameters :
-l LANG_CODE : Force a specific language (E.g. : EN, FR, NL_BE, ...)
-m MODEL     : Force a specific model (E.g. : TS100 or TS80)
-h           : Show this help message
INFO : By default, without parameters, the build is for all platforms and all languages
```
The new script has been tested on git bash on Windows and on Linux
Each time a new "translation_*.json" file is added by a contributor, the build script has to be updated
The build script impose to build all languages for all models
* **What is the new behavior (if this is a …
=> New build.sh script : detect languages with translation_*.json files

workspace/TS100/Makefile
I suspect that since -flto was added listing generation wasn't working.
-ffat-lto-objects allows tools like objdump to still work by including
both the internal compiler representation (for LTO) and generated code
in the .o files. It increases the compile time from 12s to 17s on my
machine but I think it is small enough cost for the benefit.
=> Enable flt-lto-objects for listing generation

workspace/TS100/build.sh
The highest version of bash shipped by vanilla macOS is 3.2, and it will stay like that for the foreseeable future (bash being removed as default in 10.15 is a strong indicator for that).
The build.sh script used Bash 4.x syntax for enumerating available translations - this patch dials back the clock to Bash 3.x making things work again on macOS and (hopefully) still maintaining functionality on other platforms that use a newer version of Bash.
```bash
❯ ./build.sh
*********************************************
Builder for the
Alternate Open …
```
=> Fix build on macOS

Bootup Logo/python_logo_converter/img2ts100.py
This should fix issues people have been having with the Python logo converter script producing invalid HEX files when used with DFU version 3.45 (issues #460 and #437).
The Python converter script works under Windows but not macOS. When run under Windows, the correct line ending of "\r\n" is output to the HEX file. But under macOS, the line ending is just "\n", which the iron rejects (when the USB MSD re-appears, the extension changes to .ERR).
A previous pull request (#491) addressed this issue for Windows users. Before that pull request, the script was generating "\r\r\n" under Windows, which the iron also rejected. However, this PR also broke …
=> changed Python logo converter to use correct line endings on all OSes

workspace/TS100/Core/Inc/LIS2DH12.hpp, workspace/TS100/Core/Inc/MMA8652FC.hpp, workspace/TS100/Core/Src/LIS2DH12.cpp, workspace/TS100/Core/Src/MMA8652FC.cpp, workspace/TS100/Core/Src/main.cpp
XYZ acceleration data is processed in a better fashion to be used in the control loop.  If less time is spent waiting for accelerometer data to be ready maybe reading frequency can be bumped up a bit for more responsive operations.
I2C accelerometer data is preprocessed to be in little-endian format before being used by the control loop. However:
* LIS2DH12 data is already in little-endian format as it comes out of the wire, yet the data is read byte by byte and manually converted into little-endian 16 bits integers in-memory.
* MMA8652FC data is in big-endian format, but the conversion step does not make use of the `REV16` opcode which performs …
=> Speed up accelerometer driver data processing.

History.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, README.md, Translation.md, development.md, menu.md, power.md
Fixed up grammar, trailing newlines, missing end of lines, removed and added dots at ends of sentences where they should(n't) be.
Also fixed the make example which was using the wrong flag (J instead of j).
As a note History.md is not up to date with the current release.
=> Grammar and other small fixes

Flashing/flash_ts100_linux.sh
Miwer commented in issue #11 that on Mint 17.3 lsblk does not escape
potentially unsafe characters like it does on Fedora (lsblk v2.32.1). So
broaden the grep match expression to catch both posibilities.
(What changes might users need to make in their …
=> Update Linux flash script

workspace/TS100/Core/Src/hardware.cpp, workspace/TS100/Core/Src/main.cpp
This is fairly simple one overall,
One of the voltage steps in the old code was in a bad order for QC, so on some devices 12V would drop out and on some it would work fine.
This is a bit of a cleanup as well :)
=> Fixing QC 12V

workspace/TS100/Core/Inc/OLED.hpp, workspace/TS100/Core/Src/OLED.cpp, workspace/TS100/Core/Src/main.cpp
Introduced new function OLED::drawAreaSwapped() for drawing images where
the octets are reveresed endianess in 16-bit words.
Fixes a TODO in the code:
`// TODO REDUCE STACK ON THIS ONE, USE DRAWING IN THE READ LOOP`
This change drastically reduces the stack usage of the showBootLogoIfavailable() function and cleans up the function.
showBootLogoIfavailable() uses 408 bytes of stack.
You can check this by compiling with the -fstack-usage flag in gcc. I then found the most stack consuming functions.
`$ cd …
=> Reduced stack usage in showBootLogoIfavailable().

workspace/TS100/Core/Src/GUIThread.cpp, workspace/TS100/Core/Src/OLED.cpp, workspace/TS100/Core/Src/TipThermoModel.cpp, workspace/TS100/Core/Src/TipThermoModel.h, workspace/TS100/Core/Src/main.cpp
Fix:
Remove tip disconnection warning. 
Fix leading zeros (again)
Closes #551 
Setting the target temperature too high can cause the tip disconnection to trigger and stop the iron heating.
Also fixed missing zeros in some of the number displays.
=> Fix: Remove tip disconnection warning. Fix leading zeros (again)

Translation Editor/translation_en.json
Removed '<C>' (Centigrade) symbol from SleepTemperature description and further tweaked some descriptions to match/be more similar to each other.
Removed <C> symbol from desc (as Fahrenheit is also supported) and attempted to unify the formatting of other desc strings.
(What changes …
=> Further en desc tweaks

workspace/TS100/Core/Src/GUIThread.cpp
It's needed because as of now the alert overlaps the custom bootlogo
Bug fix
The alert overlaps with a custom boot logo
The screen is cleared before showing the alert
No
Fix not tested locally because I don't have a full stm32 toolchain on my pc, but it should be …
=> Clearing screen before showing settings reset alert

Translation Editor/make_translation.py
using "git rev-parse --short=7 HEAD" to be sure we always get the commit hash.
=> bugfix - git hash returns tags (if set) instead the short hash

workspace/TS100/Core/Src/GUIThread.cpp, workspace/TS100/Core/Src/gui.cpp
Lowering min temp from 50C to 10C
https://github.com/Ralim/ts100/issues/620
User can select 10C as min temp for soldering/sleep
=> Lowering min temp to 10C

workspace/TS100/Core/Src/gui.cpp
Advanced settings menu has 9 entries so the thumb ends up being one
pixel high and on the 9th menu it ends up being closer to the middle of
the screen rather than the end. This patch fixes it.
=> Fix scrollbar thumb position for long menus

workspace/TS100/Core/Src/gui.cpp
The values are only two digits so do not overwrite the end of the menu
item string.
Fixes: #658.
=> Fix "Temp change short/long" menu display

upgrading.md
Documentation update: Add mention of not using alternative file managers / copy handlers, similar to wiki documentation.
Resolves #544
=> Upgrading.md - Use file explorer, not alternatives when upgrading on Windows

workspace/TS100/Makefile
When a symbol is used from inline assembly, LTO compiling and linking
process becomes more picky with regard to the order of compile/linking
units.
Specifically, when FreeRTOS/Source/portable/GCC/ARM_CM3/port.c comes
before FreeRTOS/Source/tasks.c in find results, the build fails with
undefined reference to `pxCurrentTCB' error.
To workaround the issue, do the same as we already have for
vTaskSwitchContext.
Note: different order affects resulting binary (.text section) size:
39924 with the wrong order and 39884 with the correct.
Fixes #685.
- [] Are there …
=> Fix FTBFS due to LTO being more sensitive to file order

workspace/TS100/Core/BSP/BSP.h, workspace/TS100/Core/BSP/Miniware/BSP.cpp, workspace/TS100/Core/BSP/Miniware/Setup.c, workspace/TS100/Core/BSP/Miniware/preRTOS.cpp, workspace/TS100/Core/Inc/power.hpp, workspace/TS100/Core/Src/power.cpp, workspace/TS100/configuration.h
With this a TS-I tip is usable with a small netbook 19 V / 30 W PSU with
power limit set to 40 W (38.9 W is reported during the heating up
stage). Without this the device just reboots on attempt to turn on the
heater (unless the power limit is set to 10 or even 5 W).
This code doesn't affect maximum power available and allows up to 73 W
when a beefy 24 V / 96 W PSU is used.
Should be useful for all models, not just TS100.
The fixed comments are based on calculations, not measurements!
Supposed to fix #693. …
=> [PoC] limit maximum power more efficiently

Translation Editor/translation_it.json
Small fix in Italian translation
"PUNTA NO" means "no tip", whereas "KO" means not ok
=> Fix BadTipString in Italian translation

workspace/TS100/Core/BSP/Miniware/Model_Config.h, workspace/TS100/Core/Drivers/MSA301.cpp, workspace/TS100/Core/Drivers/MSA301.h, workspace/TS100/Core/Drivers/MSA301_defines.h, workspace/TS100/Core/Threads/GUIThread.cpp, workspace/TS100/Core/Threads/MOVThread.cpp
Adding support for the new MSA301 for the newer 1.2 version of the TS80P
Closes #755
=> Feat add msa301

workspace/TS100/Core/BSP/Miniware/Model_Config.h, workspace/TS100/Core/BSP/Miniware/fusb302b.cpp, workspace/TS100/Core/BSP/Pine64/I2C_Wrapper.cpp, workspace/TS100/Core/Inc/main.hpp, workspace/TS100/Core/Src/main.cpp, workspace/TS100/Core/Threads/MOVThread.cpp, workspace/TS100/Core/Threads/POWThread.cpp
Small improvement by moving QC out to its own thread.
Small bugfix for the LIS for #768 while i was testing TS80P.
This is 90% cleanup work, but  _may_ help with compatibility by spawning PD threads earlier on.
=> Cleanup power into its own thread and bugfix LIS flipped mounting

workspace/TS100/Makefile
Change the generated targets to be the actual object files to be build.
Previously the target name was the dependency file itself. As no other
targets required the dependency file, those computed dependencies were
never used.
Build system bugfix.
No automatic source file dependencies are used during build.
Automatic source file dependencies are taken into account.
* **Steps to reproduce**:
```sh
$ make
...
Lots of output
$ make
Building for Pine64 
make: Nothing to be done for 'all'.
$ …
```
=> TS100: fix make dependency computation

Translations/translation_lt.json
o The changes have been tested locally on both TS80P (PCB4) and TS100 (PCB2).
o No offscreen texts, everything fits.
o "Gain" was named to "Speed" in LT, because "Gain" only translates to money-gain or achievement-gain. Haven't found it menus, so couldn't test it visually...
Have a nice day!
=> Updated Lithuanian translation. Fixed some offscreen texts.

source/Core/Threads/GUIThread.cpp
(Bug fix, feature, ~~docs update~~, ~~...~~)
- #825
- The long-press temperature change acceleration does not reset after releasing the button.
- Long-pressing to enter temp. adjust mode now waits for a button state change before handling more button input.
- The long-press temperature change acceleration resets after releasing the button.
=> Fix temp. adjust menu button behaviour

.github/workflows/push.yml, LICENSE_RELEASE.md
This adds `LICENSE` and a new `LICENSE_RELEASE.md` to the GitHub action workflow artifact outputs.
@Ralim  I think this should be appropriate, but if you find any issues, feel free to edit the files before merging
Closes #824
=> Add copyright and license notices to release

docker-compose.yml
Bug fix in the build environment.
On SELinux enabled Linux systems like Fedora, `build.sh` fails with the following error:
```
Creating ironos_builder_run ... done
/bin/bash: /build/ci/buildAll.sh: Permission denied
```
This is because SELinux forbids to mount `/home` directories in a Docker container.
`build.sh` runs on SELinux machines because Docker is explicity permitted to mount the `/home` directory. See [here](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label).
=> Fix docker build on Fedora and other SELinux enabled systems

source/Core/Src/gui.cpp
Added two new steps in the long step config: short step (=1) and half long step (=5). This allows swapping of short and long press behavior.
Feature change
IronOS permits to change the temperature by either a short press or long press of the keys. By default, a short press changes the temperature by 1°C, while a long press changes it by 10°C.
I wanted to swap the behavior, so the temperature is changed by 10°C steps with a short press, and can then be "fine-tuned" with a long press. To me this feels more natural than the current behavior.
The temperature steps can be configured in the settings, although the settings only permit certain values. …
=> Change temperature steps for long step config

Translations/make_translation.py
This is a bugfix to only use bdflib when needed.
This
a) allows the compilation of non-cjk languages without having it installed.
b) speeds up the translation generation for non-cjk languages.
=> make_translation.py: only use bdflib when necessary

source/Makefile
This adds more Makefile dependencies to make the translation generation more robust in the face of changes.
See #860
=> translations: track more generation dependencies

source/Core/BSP/Pine64/BSP_PD.c
Add 18v @ 2.4A usb-pd.
With my adapter it falls back to 15v.
It switches to 18v correctly.
So I got this adapter from [aliexpress](https://www.aliexpress.com/item/4001316262433.html) because it's cheap and comes with decently flexible cable.
However, it can't use 20v @ 2.6a due to power limit, so instead I've added 18v @ 2.4a to hopefully make it a little better than 15v @ 2a.
=> Add 18v for pinecil

source/Core/Src/gui.cpp
Regression: No hold time on the last value when incrementing an option
Fixes https://github.com/Ralim/IronOS/issues/881
=> Fix: no hold time on the last value when incrementing

source/Core/Threads/GUIThread.cpp
In detailed soldering view add '+' symbol after the temperature to indicate active boost mode (when active)
Feature
No indication of boost mode in detailed soldering view
Indication added as a '+' character displayed after the tip temperature.
I've used existing glyph. '+' made the most sense.
Maybe we want to introduce smaller version of symbol 2 (up arrow) to be consistent with the normal view?
On the other hand - the detailed view is not used very often, so maybe "+" will suffice?
=> In detailed soldering view add '+' for boost

source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp, source/Core/Src/gui.cpp, source/Core/Src/main.cpp, source/Core/Threads/GUIThread.cpp
Refactoring.
The font style is now passed as a parameter when printing the chars/strings instead of being a global state set by `setFont`.
**Motivations:**
1. I don't like the font setting being a global state. Keeping track of the current font is not so straightforward.
2. Moving the font size handling to `drawChar` makes it easier to make it draw chars in different width in the future.
3. Just messing around really
**Impact on build size:**
This change appears to have shrunk the binaries …
=> Refactor font style to be set when printing

Translations/make_translation.py, source/Core/Inc/Translation.h, source/Core/Src/gui.cpp, source/Makefile
Refactoring.
Use enum instead of integer literals to index settings descriptions, with more compile-time checking.
=> Refactor: Use enum to index settings descriptions

Translations/make_translation.py, Translations/make_translation_test.py, Translations/translations_def.js, source/Core/Inc/Translation.h, source/Core/Inc/gui.hpp, source/Core/Src/Translation.cpp, source/Core/Src/gui.cpp, source/Core/Threads/GUIThread.cpp, source/Makefile
- ✔️  The changes have been tested locally
- ✔️  There are no breaking changes
- Make translation strings into one contiguous block
- Index individual strings using 16-bit integer offsets
- Group translation string indices into a single struct
I want to make it so that the translation data (excluding font table) can be compressed in ROM and decompressed to RAM on boot, which should help reduce ROM size for multi-language builds. For multi-language use, only the active language needs to be extracted to RAM. I already had a prototype with compression working, using https://github.com/janding/lzfx (would like to try other compression algorithms, but when I tried …
=> Change internal representation of translation strings

source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp, source/Core/Src/gui.cpp
Feature: Added a scroll-down animation when changing menu items.
Part of what's mentioned in #892.
When changing to the next menu item, the screen changes directly with no transition animation.
When changing to the next menu item, the screen changes via a scroll-down animation.
This change involves changing some of the OLED command parameters, so this may require some careful review.
If the screen gets rotated when the scroll-down transition is playing, the transition becomes weird. The screen gets refreshed after the transition has finished playing, so I don't …
=> Impl. menu item scroll down animation

source/Core/Threads/GUIThread.cpp
If the iron is in sleep mode it is now possible to shutdown with
a long press on the back button without reheating in-between.
Feature
If the iron is in sleep mode (in my case via the hall sensor) it is not possible to exit soldering mode without leaving the sleep mode. This causes an unnecessary heating of the tip before you can exit soldering mode via a long back button press.
It is now possible to shutdown directly from sleeping mode with a long back button press.
=> Enable shutdown from sleep mode

Documentation/Flashing.md
there was a dot included as code block after .bin in line 9
docs
typo in the Flashing Guide
=> Fix typo in line 9 of Flashing.md

Translations/translation_BG.json, Translations/translation_CS.json, Translations/translation_DA.json, Translations/translation_DE.json, Translations/translation_EN.json, Translations/translation_ES.json, Translations/translation_FI.json, Translations/translation_FR.json, Translations/translation_HR.json, Translations/translation_HU.json, Translations/translation_IT.json, Translations/translation_JA_JP.json, Translations/translation_LT.json, Translations/translation_NL.json, Translations/translation_NL_BE.json, Translations/translation_NO.json, Translations/translation_PL.json, Translations/translation_PT.json, Translations/translation_RU.json, Translations/translation_SK.json, Translations/translation_SL.json, Translations/translation_SR_CYRL.json, Translations/translation_SR_LATN.json, Translations/translation_SV.json, Translations/translation_TR.json, Translations/translation_UK.json, Translations/translation_YUE_HK.json, Translations/translation_ZH_CN.json, Translations/translation_ZH_TW.json
With this, I tried to update all the present languages to the most recent state in terms of consistency.
Please feel free to correct certain expressions, in the different languages, maybe I missed something here and there. 😅
1. I mostly changed from **`<>`** to **`()`**, although I left some custom choices in certain cases alone.
2. I tried to get the **`Auto start`** description for all languages set.
My intention was, to **give the user an idea** and than they could change it to the way it should sound in the respective language.
kind regards
=> languages (certain unifying)

Documentation/DebugMenu.md, Documentation/Development.md, Documentation/Flashing.md, Documentation/GettingStarted.md, Documentation/Menu.md, Documentation/Power.md
=> Fix documentation typos

Documentation/Flashing.md
The URL used is a list of Miniware soldering irons each of which include links to their own firmware downloads.
=> Add link to Miniware official website

Documentation/Flashing.md
It seems the common wisdom at this point is to flash without the explicit erase if `dfu-util` is unable to complete the erase.
Documentation-only update.
Resolves #820.
=> Alternate flash command for Pinecil w/o mass-erase

source/Core/Threads/GUIThread.cpp
This is a rework of the advanced views to make it more organized and useful
Change :
- Remove all the text ( was taking too much space, specially when translated, and units tells us what the value is)
- Make the tip temp large ( better visibility )
- Value have fixed position ( no more clipping from too long translated text )
- Remove the set temperature ( I find it less useful than a large tip temp )
- Make the cool down temp blink if option set ( timing : on 700 ms | off 300ms )
Soldering view :
Idle view :
=> Rework of advanced view

Documentation/Development.md, source/Makefile
Feature: Added a parameter to allow custom language combinations to be selected at build time.
Docs Update: Updated and clarified how to use `make` to build IronOS on macOS/Linux.
A few large preset language combinations defined in the `Makefile` can be built, limiting the multi-language feature to the Pinecil.
Smaller custom language combinations can now be defined in the `make` command, allowing users of devices other than the Pinecil to reap the benefits of having a multilingual firmware as well.
=> Add custom multi-language build options and improve build docs

source/Core/Src/gui.cpp
Please refer to https://github.com/Ralim/IronOS/issues/1140 for more details.
Tested this on both **TS80P** & **Pinecil**.
Worked well for both of them!
=> tackling issue #1140

Flashing/flash_ts100_linux.sh, build.sh, ci/buildAll.sh, setup.sh, source/build.sh, start_dev.sh
Modifies shell scripts to be use a more generic /bin/sh where possible with minor changes for portability and otherwise has small changes in variable quoting and such as recommended by the shellcheck utility.
The source/build.sh script has been left as a bash, as it uses a lot of array functionality that isn't present in POSIX.
=> Generic shellscripts

source/Core/Threads/GUIThread.cpp
and some minor changes to the detailed view
=> fixed detailed view for lefties

Flashing/flash_ts100_linux.sh
- Bug fix: Fix the following errors due to forgotten brackets in a test.:
```Remounting config disk drive
rmdir: impossible de de supprimer « /tmp/ts100 »: Device or resource busy
Flash result:
/tmp/ts100/ts100.rdy
rmdir: impossible de de supprimer « /tmp/ts100 »: Device or resource busy
```
- Add a method to automatically check if the flash is done correctly or not.
The user no longer has to read the list of files on the partition and deduce whether everything is ok or not.
Please note that error messages in the checking function are now colored for better and faster understanding (in my opinion);
BUT, this requires to use bash instead of the legacy sh …
=> Fix flash ts100 linux

Documentation/Logo.md
Not all people will have the knowledge to understand what it means to use any objcopy command.
Therefore, the default should be an objcopy, which is easy to obtain on Linux.
- [✓] The changes have been tested locally
- [✓] There are no breaking changes
docs
=> Update Logo.md - simplify the objcopy command

source/Core/Src/Settings.cpp
Closes #1116 last remaining issue
=> Patch settings decrement to honour increment size and not skip max

Translations/make_translation.py, source/Core/Threads/GUIThread.cpp
I don't know, if it's only me, but I think this should be limited only to devices supporting this feature.
Otherwise this may cause confusion and unnecessary questions about why the hall sensor is turned off (and how to turn it on) on certain irons (all current ones except for the Pinecil).
I've tested this on my TS80P and the Pinecil. It worked for both!
However CI spits out an formatting error. 🤷‍♂️ (I could not figure out what's wrong!)
=> HALL only on Pinecil

source/Core/BSP/Miniware/BSP.cpp, source/Core/BSP/Miniware/configuration.h, source/Core/Threads/PIDThread.cpp
=> TS100 warning fix (#1192)

Translations/make_translation.py, source/Core/Drivers/USBPD.cpp, source/Core/Drivers/USBPD.h, source/Core/Threads/GUIThread.cpp
Expanding the shown type in the debug menu to indicate if VBus is connected or not.
This allows user to check the VBus mod presence on a Pinecil for use over 21V
Would love _any_ pinecil testers (both modded and not).
It should show `PD W. VBus` if you have not done the mod, and `PD No VBus` if you have done the mod.
=> Pinecil mod detection

source/Core/BSP/Pine64/configuration.h, source/Core/Threads/GUIThread.cpp
https://github.com/Ralim/IronOS/pull/1215#issuecomment-1036755827
FYI: @discip
=> Only vbus mod check on pinecil

source/Core/BSP/Miniware/configuration.h, source/Core/Drivers/LIS2DH12.cpp, source/Core/Drivers/LIS2DH12_defines.hpp, source/Core/Drivers/SC7A20.cpp, source/Core/Drivers/SC7A20.hpp, source/Core/Drivers/SC7A20_defines.h
=> TS80P Accelerometer version detection again

Documentation/Flashing.md
The PINE64 Updater tool does support the latest releases. I almost did not try it because of the statement in this doc, but it flashed 2.17 to my pinecil just fine.
Doc update
=> Update pinecil flashing instructions

Documentation/Flashing.md
Add a note about USB autosuspend preventing firmware updates via `dfu-util` for the Pinecil to the flashing instructions for Linux. I stumbled over the problem from #1148 and it took me some time to find the issue with the solution. Thus, I think this belongs into the troubleshooting section of the documentation. Credits and thanks to @slackista for figuring this out and @edubxb for the udev rules.
=> Add USB autosuspend to troubleshooting for Pinecil

.github/workflows/push.yml, Dockerfile, source/Core/Drivers/BootLogo.cpp
Fixes the infinite delay setting for the bootup logo
#1285
=> Infinite logo

source/Core/Drivers/Buttons.cpp
Refactoring, bug fix
* Changed: Do not generate a spurious `BUTTON_BOTH` when releasing a two-button long-press. Previously, if you released the two buttons not at the same time, every check starting at the first release would update `previousStateChange`, and the second release would misinterpret `previousStateChange` as a button *press* time and act like a two-button short-press.
* If desired, the new code could be changed to *always* generate `BUTTON_BOTH` releasing a two-button long-press.
* Fixed: Every single-button press generates either one press-release event or 1+ long-press …
=> Cleanup getButtonState(), fix button handling bugs

source/Core/BSP/BSP_Power.h, source/Core/BSP/MHP30/Power.cpp, source/Core/BSP/Miniware/BSP.cpp, source/Core/BSP/Pine64/BSP.cpp, source/Core/Drivers/USBPD.cpp, source/Core/Drivers/USBPD.h, source/Core/Src/power.cpp, source/Core/Threads/GUIThread.cpp
This updates the usb-pd library to add USB-PD EPR support.
At the moment this will _not_ increase the negotiated voltage of any products.
This is just to get the updated library in and testing
=> USB PD EPR Basics

source/Core/Threads/GUIThread.cpp
- [✓] The changes have been tested locally
- [✓] There are no breaking changes
Feature
When plugging in the iron with both autostart and a boot logo/animation enabled, the iron doesn't start heating until after the boot logo/animation finishes. If the iron heats up slowly, this means that the user either has to wait that much longer to use their iron or disable the boot logo/animation altogether.
The iron will preheat to your sleep temperature (as long as it's no more than 75*C, otherwise it will heat to 75) during the boot logo/animation, then heat the rest of the way afterwards.
* …
=> Allow preheating iron during boot logo (fixes #1334)

Documentation/Logo.md, README.md
-There are no breaking changes
- Document updates & user Instructions
=> Updates to documents

source/Core/Drivers/OLED.cpp
Buttons can now skip an animation in progress
Animations are faster
Should close #1330
=> Animation non block

source/Core/Src/settingsGUI.cpp
Should Close #1379
Bumps menu timeout.
This is really only there so that an iron left in the menu will eventually shutdown.
So fairly harmless to have this be longer.
=> Bump timeout for menu actions

.github/workflows/push.yml, source/Makefile
We have moved on to all languages being larger.
So it works out better now on average to always run compression over them.
=> Always use compressed data even for single languages

Documentation/Settings.md
=> cleared up some wording along with some typo fixes

source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp
Using a small checksum on the OLED update; to only send the screen contents data.
This is to reduce activity on the I2C bus when we dont need to.
=> Only send on display change

source/Core/Threads/GUIThread.cpp
Did not calibrate if *handle temp* was higher than *tip temp*.
=> fixed CJC calibration condition

Documentation/Menu.md
=> updated Menu.md

source/build.sh
>**Bug fix:** Command line build customizable multiple firmwares with user defined languages and models was not possible. 
>This will expanded the build script to build customizable multiple languages and models firmwares.
>Same as before with the additional possibility to build customizable selectable languages and models.
**This was working:**
> - build.sh                                                (Build all models and all languages)
>- build.sh -l EN -m TS100                     (Build one language and model)
**This was **not** working:** (Which is fixed with now.)
>- build.sh -l …
=> Expanded the build script to build customizable multiple languages and models firmwares

source/Core/Threads/OperatingModes/Soldering.cpp
When the estimated wattage is > 99.9W we drop the decimal and just print 100W
#1496
Closes #1496 when merged
=> Drop decimal when > 99.9W

source/Core/BSP/Pinecilv2/ble_handlers.cpp, source/Core/Threads/OperatingModes/DebugMenu.cpp, source/Core/Threads/OperatingModes/HomeScreen.cpp, source/Core/Threads/OperatingModes/OperatingModes.cpp, source/Core/Threads/OperatingModes/OperatingModes.h, source/Core/Threads/OperatingModes/Sleep.cpp, source/Core/Threads/OperatingModes/Soldering.cpp
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
feature
**What is the current behavior?**
nothing is returned for the Operating Mode BLE characteristic
**What is the new behavior (if this is a feature change)?**
it will now return an int depending on what mode it is in.
idle -> 0
soldering -> 1
sleeping -> 2
settings menu -> 3
debug menu -> 4
**Other information**:
=> track and return Operating Mode with BLE

README.md
Add explanation why TS80 is no longer recommended
Docs update
=> Update README.md to explain why TS80 is not recommended

Documentation/Flashing/Pinecil V1.md, Documentation/Flashing/Pinecil V2.md, README.md
- update very outdated Pinecil V2 instructions & links
- update Pinecil V1 instructions & links
- add an _optional_  badge for total number of contributors-anon. you  can strip this out if you don't like or too cluttered.
if  just a regular contributors number is desired, change the badge to
`![GitHub contributors](https://img.shields.io/github/contributors/ralim/ironos?color=blue)`
=> Update documents, esp. Pinecil V2 instructions

README.md
Fix small typo from #1588
Docs update (typo fix)
From #1588 newly added info about TS80 is split in new line at the end due to typing mistake.
* **What is the new behavior?**
=> Update README.md to fix small typo

Translations/translation_EL.json
Signed-off-by: Devnol <pgkoutsoumanis@gmail.com>
Re-did the EL translation for the dev branch, adding in new strings wherever necessary.
=> Add new EL translation strings

Documentation/Flashing/Pinecil V2.md, Documentation/GettingStarted.md
This just updates the getting started page description of the startup icons. It talks about a "spanner like icon" for the settings menu, but that didn't reflect the latest release or the screenshot image above this section. I don't know if that is a legacy icon, but the current settings icon looks like a set of three slider controls. I updated this section to reflect that.
[Edit: also threw in a quick Markdown syntax typo fix. Hope that isn't a problem.]
docs update
=> Update settings icon description

source/dfuse-pack.py, source/metadata.py
Unify sha-bangs for python scripts - put the same line as in the other py scripts.
=> Unify sha-bangs for python scripts

source/Makefile
Hello.
* Command `make  -C source  model=TS80P  firmware-EN` from root directory should produce build.
* What actually happens:
```
$ make -C source  model=TS80P firmware-EN
make: Entering directory '/root/tree/ironos/source'
Building for Miniware 
Building file: ./Startup/startup_stm32f103t8ux.S
[skip log]
echo "#include <configuration.h>" | arm-none-eabi-gcc -dM -E -D VECT_TAB_OFFSET=0x4000U -mcpu=cortex-m3 -mthumb -mfloat-abi=soft -I./Core/Inc -I./Core/brieflz -I./Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I./Middlewares/Third_Party/FreeRTOS/Source/include -I./Core/Drivers -I./Core/BSP -I./Core/Threads -I./Core/Threads/OperatingModes -I./Core/Threads/OperatingModes/utils -I./Core/Drivers/usb-pd/include -I./Core/BSP/Miniware …
```
=> source/Makefile: update for -C support

Translations/make_translation.py, source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp, source/Core/Threads/OperatingModes/DebugMenu.cpp, source/Core/Threads/OperatingModes/OperatingModes.h, source/Core/Threads/OperatingModes/Soldering.cpp, source/Core/Threads/OperatingModes/utils/SolderingCommon.cpp
[UX perspective](https://github.com/Ralim/IronOS/issues/1708)
But nasty hacks may apply, sorry :(
A few comments:
* I was considering a few approaches - this one turned out to be less invasive.
* As much as strange trick with _overloading_ `OLED::print` may look - it works **for my own surprise** and, what's more important - doesn't break **any other visible** OLED functionality.
* I thought that _shrtn_ existed strings anyway better than adding another one set of arrays of chars considering how valuable space is for some supported devices.  
Waiting for a feedback crossing fingers.
=> Show power source type on detailed screen in soldering mode (#1708)

source/Core/BSP/Miniware/BSP.cpp, source/Core/BSP/Miniware/Power.cpp, source/Core/BSP/Miniware/Setup.cpp, source/Core/BSP/Miniware/configuration.h, source/Core/BSP/Sequre_S60/configuration.h, source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp, source/Core/Src/settingsGUI.cpp
Fixing up support for 128x32 OLED's a bunch to remove all the crap around the edge and lay the groundwork for better graphics
Also caught a few small edge cases from earlier PR's im throwing in for ease.
I've run this on : PinecilV2, TS80P, TS100,TS101 and all seems to be good. If any issues let me know of course :)
=> Larger OLED Support

source/Core/BSP/MHP30/configuration.h, source/Core/BSP/Miniware/configuration.h, source/Core/BSP/Pinecil/configuration.h, source/Core/BSP/Pinecilv2/configuration.h, source/Core/BSP/Sequre_S60/configuration.h
=> A bit of clean-up & update configuration.h files

source/Core/BSP/Miniware/Software_I2C.h, source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp
trying to resolve https://github.com/Ralim/IronOS/commit/691abd5caa5ae5d755ae2d2421f124c06b1e4df8#commitcomment-119722175
@discip  Could you please test if this changes anything 🙇🏼
=> Adjust divider

source/Core/Drivers/USBPD.cpp
Currently, IronOS increases the tip resistance by 0.5 ohms for the purposes of USB-PD negotiation.  On the Pinecil V2, this can cause issues with power supplies that only supply 60W, such as the Framework 60W supply.  At 6.2 ohms, 20V will produce 3.2A, but at 6.7 ohms it will produce 2.985 ohms.  This 0.5 ohms increase will cause the V2 to negotiate 20V, draw more than 3A, and trip the overcurrent protection, causing it to reboot.  Removing this increase will therefore cause it to fall back to the next highest voltage it can achieve.
[On devices such as the Framework …
=> Remove 0.5 ohm increase to resistance

source/Core/BSP/Pinecilv2/Setup.cpp, source/Core/BSP/Pinecilv2/bl_mcu_sdk/bsp/bsp_common/platform/bflb_platform.c, source/Core/BSP/Pinecilv2/bl_mcu_sdk/drivers/bl702_driver/bl702_flash.ld, source/Core/BSP/Pinecilv2/bl_mcu_sdk/drivers/bl702_driver/startup/drv_mmheap.c, source/Core/BSP/Pinecilv2/bl_mcu_sdk/drivers/bl702_driver/startup/drv_mmheap.h
A different tact to try and fix #1661 
#1661 
Uses their custom ram allocator  & different linker layout
=> Try side-port of different linker and ram for PinecilV2

Makefile, scripts/IronOS.Dockerfile
Fix a tiny bug in the top-level `Makefile`.
In some environments (such as docker shell inside `alpine 3.16`) instead of transforming escape sequences on output respectively, output shows `\t`s and `\n`'s as is.
Replace `\t`s and `\n`'s by spaces and outputs of new lines explicitly.
Also I took some liberty to switch `WORKDIR` for the container. Currently, after you start a docker shell and want to do something with sources, you must manually do extra command (like `cd source`) to jump into source tree to keep working with scripts & sources. This little change …
=> Fix echo in top-level Makefile for some environments

Documentation/index.md
Update `Documentation/index.md` which is exported as [ReadTheDocs online documentation](https://ralim.github.io/IronOS/).
As described in [this report](https://github.com/Ralim/IronOS/issues/1552):Ralim#1552, if a user opens the main online documentation page, there is no any information about _feedback_ to the project nor how to report a bug or ask community for help.
if a user opens the main online documentation page, there is a clear "feedback welcome" section with direct links to _github Issue report form of the project_ and _direct link to Discussions board_.
* **Other …
=> Documentation/index.md: add Feedback section (Ralim#1552) as suggested

source/Core/Drivers/OLED.cpp, source/Core/Drivers/OLED.hpp, source/Core/Src/settingsGUI.cpp, source/Core/Threads/OperatingModes/HomeScreen.cpp, source/Core/Threads/OperatingModes/OperatingModes.h, source/Core/Threads/OperatingModes/Sleep.cpp, source/Core/Threads/OperatingModes/SolderingProfile.cpp, source/Core/Threads/OperatingModes/TemperatureAdjust.cpp, source/Core/Threads/OperatingModes/utils/DrawTipTemperature.cpp, source/Core/Threads/OperatingModes/utils/PrintVoltage.cpp, source/Core/Threads/OperatingModes/utils/SolderingCommon.cpp
Implement helper function for repetitive blocks of code.
The same snippet used a few times in code base to print degree symbol & temperature symbol.
Helper function to make snippet reusable in more convenient way.
I have a couple of questions though.
Is my intuitive speculation correct that [this block](https://github.com/Ralim/IronOS/blob/d95af7d1a0ddd5a93a0827d08294c5504c9e9a94/source/Core/Threads/OperatingModes/utils/DrawTipTemperature.cpp#L17):
```
if (getSettingValue(SettingsOptions::TemperatureInF)) {
OLED::drawSymbol(0);
} else {
OLED::drawSymbol(1);
}
``` …
=> Implement printSymbolDeg() helper function as method for OLED class

scripts/deploy.sh, source/Makefile
Move check-style core logic from `source/Makefile` : `check-style` target to `scripts/deploy.sh` : `check_style_file` function.
If there is a need to maintain / modify core logic of check-style inside Makefile, it's crossing of bash syntax & makefile syntax which makes it look very inconvenient and disallow to put even per-line comments.
To change/fix/update `check-style` parsers & logic, now it represented as a shell function inside `deploy.sh`.
This is not ideal, but I think it should make it more "_maintainable_": just like for some other stuff to load off …
=> Move check-style core logic from makefile to shell script

Env.yml, scripts/IronOS.Dockerfile, scripts/ci/buildAll.sh
Tiny change of the directory name inside docker container.
The root project directory mapped/copied to `/build/source/` inside of docker container. But since there is `source` directory inside the root project directory already, sometimes it leads to ambiguity.
The root project directory mapped/copied to `/build/ironos` inside of docker container.
Plus tiny refactoring `buildAll.sh` only to use variables for directories instead of hardcoded paths just in case.
Just another one tiny _"ci beautify"_ suggestion. :)
It shouldn't affect anything else though - I tested …
=> Replace /build/source by /build/ironos to eliminate ambiguity with /build/source/source

.github/workflows/push.yml, scripts/deploy.sh
Fix github CI clang-format related check_c-cpp job.
After `check-style` logic has been moved to shell script, `make check-style` calls it but because bash is missing in the container, [script can't run the check](https://github.com/Ralim/IronOS/actions/runs/5605990076/job/15187555096#step:5:13)!
It _should be_ fixed with these changes.
**I'm terribly sorry!!!** But it seems this particular job is cursed! It's the second time already when according to log there is a problem but github CI just can't track down such ease-to-automate checks for users. Not excusing my …
=> Fix github CI clang-format related check_c-cpp job

.github/workflows/push.yml, Makefile, source/Makefile
Simplifying commands in `push.yml`.
`push.yml` may contain extra commands.
Now since the permissions for script files are fixed and `make`-based build system is _almost fully_ location-agnostic we can call some commands on github CI in a shorter way.
Tested locally & successfully all the commands from `push.yml` but let's see what github CI will tell about that. I will check & double check the logs & artifacts to make sure that all the builds steps are being performed as expected after creating PR.
=> Simplify commands for jobs in push.yml

.github/workflows/push.yml
Fix #1764 bug (but maybe introduces new bugs).
Multi-lang builds for PinecilV2 crash with link-related errors due to nuances of calling multiple targets in parallel using external helper Makefile.
Hopefully fixing crashes of multi-lang builds for PinecilV2 by calling `source/Makefile` directly using `-C` option without involving top-level `Makefile`.
See #1764 issue report for the full details.
This probable fix has been tested locally. While problematic behavior is reproducible with 99% rate, after just switching a call from `make` to `make -C` in `test.sh` more …
=> push.yml: probable fix #1764

Documentation/Bluetooth.md, Documentation/Troubleshooting.md
Updating Docs for BLE.
Closes  #1656 
=> BLE getting started document

.github/workflows/push.yml, Documentation/DebugMenu.md, Translations/make_translation.py, scripts/deploy.sh
Implement proper git SHA ID marking for builds during pull-requests.
If a build has been produced on github CI **after creating pull request**, then git SHA ID doesn't equal to the latest git SHA ID in a user's branch.
Retrieve proper git SHA ID for marking builds during pull-requests using github CI environment variables through `push.yml` features.
As far as I understand (according to some pieces of information), here is what github does on builds for pull-requests:
- `git checkout COMMIT-ID_from_user_branch` 
- `git merge UPSTREAM`
Therefore, getting COMMIT_ID …
=> Implement proper git SHA ID marking for builds during pull-requests

source/metadata.py
Make commit SHA ID for JSON files equal to the latest commit if it's pull-request.
JSON files have commit ID which is not valid to the project tree in case of github CI builds during pull-requests.
Put proper valid commit ID into JSON files on github CI builds.
Since now a proper SHA ID can be obtained during github CI builds using changes in `push.yml`, utilize this for proper JSON tagging.
=> metadata.py: update tagging considering github CI builds

Documentation/DebugMenu.md, Translations/make_translation.py
Implement proper tagging for detached commit case.
If the project tree in a detached commit case, then tagging logic goes for "Homebrew" build which is not correct.
Check if the tree is in a detached state and if it's the case then put SHA ID only instead of trying to get branch name.
I hope this is last commit in the series considering all major possible cases for proper tagging so if there is any commit ID it doesn't lead to nowhere but allowing to ID the source tree used for a build.
=> Update tagging for detached commit case & update docs

Documentation/Logo.md
Updating documentation for the Boot Logo process
@discip  here you go
=> Update logo flashing information

source/build.sh
Update `build.sh` according to `shellcheck` recommendations.
There are four warnings for `build.sh` currently.
Update `build.sh` to remove `shellcheck` warnings.
I know that `IFS` without `read` should be ok but since `shellcheck` complains about checking arrays why wouldn't update those two as well.
=> Update build.sh to pass shellcheck checks

Makefile, scripts/deploy.sh
Add `docker-clean` sub-targets `docker-clean-image` & `docker-clean-cache` into `Makefile` to remove not only image but cache.
After doing a lot of `make docker-shell` / `make docker-build`, `make clean-full` / `make docker-clean` may remove only docker image with IronOS env but not its build cache objects.
`make clean-full` / `make docker-clean` / `./scripts/deploy.sh clean` removes **all** docker data related to IronOS env container.
I personally use docker very rarely & sporadically. And I know that the modern tendency is not to care about resources …
=> Make `make docker-clean` to remove docker build cache

source/Core/Drivers/USBPD.cpp
Reverts Ralim/IronOS#1728
Reverting this as it appears to maybe sorta help _one_ specific PSU out of lots that have been tested.
So given it helps approximately 1 charger out of 100's-100k's it has been decided in chat that this is not really worth it.
=> Revert "Remove 0.5 ohm increase to resistance"

Documentation/README.md, scripts/IronOS-mkdocs.yml
Include `Bluetooth.md` to read-the-docs site generating.
There is `Bluetooth.md` document but its content is not available in [online documentation](https://ralim.github.io/IronOS/Troubleshooting/).
Make `Bluetooth.md` content being generated for online documentation by updating related `mkdocs` configuration file.
`README.md` inside of `Documentation` is updated as well.
=> Include Bluetooth document to read-the-docs site generating

scripts/IronOS.Dockerfile
Add python packages required by `mkdocs` into docker container.
Set of commands:
`$ make docker-shell`
`# make docs`
returns error.
`make docs` generates `site` directory with static html documentation inside of a container successfully.
=> Add python packages required by `mkdocs` into docker container

Documentation/History.md, Documentation/README.md, scripts/IronOS-mkdocs.yml
* include History.md to read-the-docs site generating as Changelog
* update titles formatting for more distinguishable html output
* unify style between sections
There is `History.md` document but its content is not available online.
`History.md` content is being generated for online documentation by updating related `mkdocs` configuration file.
`README.md` inside of `Documentation` is updated as well.
=> Include History.md to online docs as Changelog

Documentation/History.md
Add change log info into `History.md` for versions `2.20` & `2.21`.
`History.md` misses change log for two previous releases.
`History.md` contains change log for two previous releases.
Also unify section sub-title as `features & changes`.
=> docs/History.md: add info for 2.20 & 2.21

source/Core/BSP/BSP.h, source/Core/BSP/MHP30/ThermoModel.cpp, source/Core/BSP/Miniware/ThermoModel.cpp, source/Core/BSP/Pinecil/ThermoModel.cpp, source/Core/BSP/Pinecilv2/BSP.cpp, source/Core/BSP/Pinecilv2/IRQ.cpp, source/Core/BSP/Pinecilv2/IRQ.h, source/Core/BSP/Pinecilv2/Setup.h, source/Core/BSP/Pinecilv2/ThermoModel.cpp, source/Core/BSP/Pinecilv2/configuration.h, source/Core/BSP/Sequre_S60/ThermoModel.cpp, source/Core/Drivers/TipThermoModel.cpp, source/Core/Drivers/TipThermoModel.h, source/Core/Inc/Types.h, source/Core/Inc/main.hpp, source/Core/Inc/power.hpp, source/Core/Src/power.cpp, source/Core/Threads/OperatingModes/utils/checkUndervoltage.cpp, source/Core/Threads/PIDThread.cpp
Key updates:
1) Unify all temperatures to be stored and managed in a common type
2) Smaller fixups for comments
3) Slight improvement to temperature regulation on Pinecil V2
4) Fix fast/slow speeds on PinecilV2
5) Re-tune PinecilV2 to handle (4)
=> Temperature code updates

source/Core/BSP/BSP_Power.h, source/Core/BSP/MHP30/BSP.cpp, source/Core/BSP/Miniware/BSP.cpp, source/Core/BSP/Pinecil/BSP.cpp, source/Core/BSP/Pinecilv2/BSP.cpp, source/Core/BSP/Pinecilv2/IRQ.cpp, source/Core/BSP/Pinecilv2/Setup.cpp, source/Core/BSP/Pinecilv2/bl_mcu_sdk/drivers/bl702_driver/std_drv/inc/bl702_pwm.h, source/Core/BSP/Pinecilv2/bl_mcu_sdk/drivers/bl702_driver/std_drv/src/bl702_pwm.c, source/Core/BSP/Pinecilv2/configuration.h, source/Core/BSP/Sequre_S60/BSP.cpp, source/Core/Threads/OperatingModes/OperatingModes.h, source/Core/Threads/OperatingModes/Sleep.cpp, source/Core/Threads/OperatingModes/utils/DrawTipTemperature.cpp, source/Core/Threads/OperatingModes/utils/SolderingCommon.cpp, source/Core/Threads/PIDThread.cpp
Basically, I've given up with the previous control scheme and have written a fairly trivial PID implementation and tuned it for my PinecilV2.
This includes:
- Made a workaround for glitchy / missed timer events
- Wrote basic PID
- Opted PinecilV2 into said PID
- Tuned PinecilV2 for said PID
#1824
#1688 
This still isnt perfect but for my testing is largely improved. Any testing would be highly appreciated. If you still get the large oscillations please let me know what tip + power supply is being used so I can attempt to …
=> Pinecil v2 tune via PID

Documentation/Flashing/MHP30.md, Documentation/Flashing/TS100.md, Documentation/Flashing/TS80(P).md, Documentation/Hardware.md
Update links to the official Miniware firmware since the original forum links are dead.
For the purpose of restoring functionality in case if something went wrong with flashing IronOS, documentation suggests to download official firmware and flash it. However, the minidso forum links are dead by now.
Hence, this update replaces dead links to new official download firmware hub-like single page by Miniware.
If [related commit to meta repo](https://github.com/Ralim/IronOS-Meta/pull/41) will be approved, before approving this PR I would like to add links to firmware …
=> Update links to the original Miniware firmware [#1840]

source/Core/Src/Settings.cpp
Turning off Bluetooth LE on PinecilV2 by default.
Bluetooth LE on PinecilV2 is turned on by default.
Bluetooth LE on PinecilV2 is turned off by default.
[Report](https://github.com/Ralim/IronOS/issues/1856).
=> Settings: disable Bluetooth LE by default (for PinecilV2) #1856

source/Makefile
_Hopefully_ fixes #1886 
Using `source/Makefile` with `BSD find` it creates extra trailing `/`s to excluded directories so they are not excluded during build process and build is failed.
Remove trailing '/`'s from variables with directory paths in `source/Makefile`.
Needs confirmation from someone with `OSX` host tools configured to build `IronOS` for verification.
=> source/Makefile compatibility with BSD find [#1886]

source/Core/BSP/Pinecilv2/bl_mcu_sdk/components/ble/ble_stack/host/gatt.c
=> fix: handle is uninitialized when BFLB_BLE_DISABLE_STATIC_ATTR defined

Makefile
Tiny update for top-level `Makefile`.
`S60P` is officially supported now but it's missing in top-level `Makefile`.
Now `S60P` is added to top-level `Makefile` so `S60P` target can be used right from the root directory.
By the way, much appreciated and deeply honored for _collaborator_ status in this incredible project, being right next to wonderful and amazing people.
P.S. I took some liberty to update and unify labels a bit, hope no one's mind.
=> Makefile: add S60P to MODELS

Translations/translation_PT.json
Some additions to the Portuguese language file as it was incomplete
Some of the available functions of the Portuguese language file weren't translated (such as: cooldown and preheat)
Changed cooldown to "arrefecer", preheat to "pré-aquecer" and their accompanying descriptions were also translated 
=> Completed PT translation file

source/Core/Drivers/USBPD.cpp, source/Core/Threads/OperatingModes/USBPDDebug_FUSB.cpp
#1906 
Up until now we have trusted non-epr chargers to set the reserved bits to 0. This instead checks EPR bit and uses that to decide if we decode as PPS or not.
=> Handle non-EPR devices not encoding PPS correctly

source/Core/BSP/Sequre_S60/BSP.cpp, source/Core/BSP/Sequre_S60/Setup.cpp, source/Core/BSP/Sequre_S60/configuration.h
Bumps the PWM rate for the Sequre S60/S60P.
For me this improves performance a fair bit.
Also added a UX filter to the display temp to make it easier to track with the eye.
=> Sequre Faster PWM

source/Core/Drivers/FS2711.cpp, source/Core/Drivers/USBPD.cpp, source/Core/Drivers/Utils.cpp, source/Core/Inc/Settings.h, source/Core/Src/settingsGUI.cpp
Small refactoring by adding `enum` for USB PD modes.
USB PD mode related code uses constants.
USB PD mode related code uses self-documenting `enum` values.
I took some liberty to update comments as well based on information provided from PR #1917 and from its _"code review"_ comment to make it more clear for those who will be looking through the code next time.
As always, let me know what you think.
=> Add enum for USB PD modes

source/Core/Drivers/OLED.hpp, source/Core/Src/settingsGUI.cpp
Implement `OLED::drawUnavailableIcon()` to simplify duplicated calls.
Multiple calls of `OLED::drawArea(OLED_WIDTH - 16 - 2, 0, 16, 16, UnavailableIcon)` in `settingsGUI.cpp` with magic constants.
Simply call `OLED::drawUnavailableIcon()` to draw `UnavailableIcon` which helps:
- hide magic constants under the hood;
- remove duplicated calls;
- simplify future updates/extends for related call in the case of need by changing logic in one single place.
Check this another one small trivial refactoring out. ;)
I'm not sure about the necessity of `inline` but I just …
=> Implement OLED::drawUnavailableIcon() to simplify duplicated calls

source/Core/Threads/UI/logic/SolderingProfile.cpp
Fixes #1939 -- this appears to most likely be a regression from baf2f26e59da8408ce49cf072441ea0ee69a41c6
In addition to the bugs noted in that issue, I observed a couple of others that are also fixed here:
- If two phases had the same target temperature, it would set the target to 0 degrees when hitting that phase.
- The target temperature could underflow when cooling down.
- The comment in the code indicated that it would reject entering profile mode if the actual temperature was greater than the defined preheat temperature, but the actual behavior was a hardcoded 55 C limit. I changed it to match what the comment said it should do.
* **What is …
=> Fix profile mode

source/Core/Threads/UI/logic/Soldering.cpp
This is an untested draft to fix a possible lock/unlock toggle loop bug when holding both buttons.
=> Possible fix for lock/unlock toggle loop

source/Core/Threads/UI/logic/OperatingModes.h, source/Core/Threads/UI/logic/Soldering.cpp
This is an untested draft to keep the locked warning for some time, independet of how long a button is pressed.
=> Keep the locked warning for some time

source/Core/Src/syscalls.c
Add stub implementations of unused _syscalls_ explicitly.
There are missed stub implementations for some _syscalls_ which leads to compile warnings for all target devices except _Pinecil_ (both versions) [like these ones](https://github.com/Ralim/IronOS/actions/runs/10376691546/job/28729207594#step:8:26):
```
/usr/lib/gcc/arm-none-eabi/13.1.0/../../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/13.1.0/../../../../arm-none-eabi/lib/thumb/v7-m/nofp/libc_nano.a(libc_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0xc): warning: _close is not implemented and will always fail …
```
=> Add stub implementations of unused syscalls explicitly

Documentation/Power.md
=> formatting fix

README.md
Add direct links to stable and the latest successful dev builds in README.
To download the latest `dev` build for the device, a user have to: go to _Actions_ tab, find successful `dev` build item, open it, scroll down to _Artifacts_, download related `zip`.
Just providing [https://github.com/Ralim/IronOS#builds](https://github.com/Ralim/IronOS#builds) link will be enough to get any type of build in one click.
This is possible through awesome [nightly.link](https://nightly.link) service using _GitHub_ _API_ to extract latest successful builds. I just did feed our …
=> Add direct links to stable and dev builds in README

scripts/deploy.sh
Test to check links to stable releases in _Builds_ section of main `README.md`.
If new stable version will be released, then we have not to forget manually update links in _Builds_ section of main`README.md`.
Autotest checks that `README.md` contains mentions of the latest stable version only.
Another one follow-up to test some parts of documentation & build content.
=> scripts/deploy.sh: add test for links to stable builds in README

source/Core/BSP/Miniware/configuration.h
=> adjusted lowest brightness threshold for TS101

.gitignore, source/Core/BSP/MHP30/configuration.h, source/Core/BSP/Miniware/configuration.h, source/Core/BSP/Pinecil/configuration.h, source/Core/BSP/Pinecilv2/configuration.h, source/Core/BSP/Sequre/configuration.h, source/Core/Threads/PIDThread.cpp, source/Core/Threads/UI/logic/Soldering.cpp
* **Please check if the PR fulfils these requirements**
This closes #1946. 
Rewriting the thermal runaway to look for a low-high delta instead of a rate of change.
This _should_ be more reliable.
Also this only checks until we are confident the hardware isn't broken (for main broken case). So it should avoid false tripping.
This is a tradeoff; where we wont detect a runaway immediately, so I have kept the check for the ADC going off the charts to find a runaway tip.
This will need _TESTING_ for confidence. But I'm posting this early for testing feedback.
* **What is the current behaviour?**
* **What is the new behaviour (if this is a feature change)?**
=> Rewrite Thermal Runaway detection

source/Core/BSP/Miniware/BSP.cpp, source/Core/BSP/Miniware/configuration.h, source/Core/BSP/Pinecilv2/configuration.h, source/Core/Inc/Settings.h, source/Core/Src/Settings.cpp, source/Core/Src/settingsGUI.cpp
Enable `Soldering Tip Type` routines for supported hardware only.
There are parts of code which are not relevant for all supported models, but yet the code is compiled & takes space on flash.
- add `TIP_TYPE_SUPPORT` macro;
- enable related functions using the macro;
- enable `TIP_TYPE_SUPPORT` only for _TS101_ and _Pinecil v2_ as main targets for this feature;
- put `Soldering Tip Type` down the list in the settings, since it's optional.
Hello. I understand that this is raw & experimental feature. And I'm sorry I wasn't around when it was implemented, because …
=> Add macro to enable tip types for supported hardware only

source/Core/Src/Settings.cpp
Set `TipTypeAuto` for _tip type_ by default in runtime.
If there is no matched tip, then `lookupTipName()` returns `nullptr`, which leads to [the problem displaying _Soldering Tip Type_](https://github.com/Ralim/IronOS/pull/2031#issue-2756657524).
Return `TipTypeAuto` as the only one reasonable default option here.
Just a #2031 follow up "safety net" suggestion: the fact that this code is under development, doesn't mean we can't start to put some air bags for the future. ;) `TIPTYPE_TS80` defined for _TS80/P_ and `TIPTYPE_JBC` is not defined at all (yet), so even …
=> Set tip type as auto by default in runtime

.github/workflows/docs.yml
Fix GitHub Actions warning for docs workflow.
There is [the warning in docs workflow](https://github.com/Ralim/IronOS/actions/runs/12875477058):
[**deploy-docs**](https://github.com/Ralim/IronOS/actions/runs/12875477058/job/35896840617#step:3:10):
```
The `python-version` input is not set. The version of Python currently in `PATH` will be used.
```
Set `python-version` explicitly for `actions/setup-python` in `docs.yml` workflow configuration file to remove the warning.
It seems that [since some time](https://github.com/actions/setup-python/issues/458) …
=> Set python-version for actions/setup-python to remove the github actions warning

.github/workflows/push.yml, Makefile, Translations/translation_UZ.json, scripts/deploy.sh
Implement very basic check for tabs and odd spaces in `json` files.
There are no any automatic code style checks for `json` files.
With every modification `json` files will be checked for tabs and odd spaces as part of CI/autotesting process.
There are some full-featured `json` linters, but the ones I saw required _nodejs_/_npm_ and other "_heavy_" toolsets, so for basic checks two calls of `grep` inside `bash` should be enough: it checks for tab as octet number `11` of tab control character (`9` in dec/hex from ASCII table), and for odd amount of spaces as …
=> scripts/deploy.sh: add handmade linter for translation-related json files to check for tabs and odd spaces

source/Core/Src/settingsGUI.cpp
moving common code out of branching inside the setProfileTemp function
cleaning of code
`setProfileTemp` function contains multiple lines of the common code inside the different branches of `if-else`
```cpp
static void setProfileTemp(const enum SettingsOptions option) {
// If in C, 5 deg, if in F 10 deg
uint16_t temp = getSettingValue(option);
if (getSettingValue(SettingsOptions::TemperatureInF)) {
temp += 10;
if (temp > MAX_TEMP_F) {
temp = MIN_TEMP_F;
}
setSettingValue(option, temp); // common code
} else {
temp += 5;
if (temp > MAX_TEMP_C) {
temp = MIN_TEMP_C;
}
setSettingValue(option, temp); // common code
}
}
```
=> refactor(core/settingsgui): code cleaning

source/Core/Drivers/OLED.cpp
Access to the inactive union members is an **undefined behavior**. 
`whole` is active member here,
https://github.com/Ralim/IronOS/blob/ab1fa2486355f7dd4bfd047ac30832439067adfd/source/Core/Drivers/OLED.cpp#L217
but the `strips` (inactive) member accessed here.
https://github.com/Ralim/IronOS/blob/ab1fa2486355f7dd4bfd047ac30832439067adfd/source/Core/Drivers/OLED.cpp#L222
Standard C++ (Working Draft):
[\[defns.undefined\]](https://eel.is/c++draft/defns.undefined)
> 3.65[defns.undefined]undefined behavior
> behavior for which this document imposes no requirements
> [Note 1: Undefined behavior may be expected when this document omits any explicit definition of behavior or when a program uses an incorrect construct or invalid data. Permissible undefined behavior ranges from ignoring the …
=> fix: accessing inactive union members

README.md
Add notice that _BLE_ is turned off in _IronOS_ for _Pinecil V2_ by default.
There is no any information about _BLE_ in _Pinecil V2_, nor that it's off by default now.
Main `REAMDE.md` provides basic information about _BLE_ in _Pinecil V2_ & its new default setting, and how to turn it on back.
This is follow-up for [very good suggestion](https://github.com/Ralim/IronOS/issues/1856#issuecomment-2608817183).
=> README.md: add notice about BLE turned off by default now

source/Core/Src/Settings.cpp
Some chargers have funky PPS.
Plus some do not want EPR be default (even though 28V is safe by designer on PinecilV2).
So take the safest option by default and make it opt-in
Request from Pinecil Chat - d​simic
=> Default to no EPR/PPS so its opt in

README.md
Main `README.md` update.
There is no mention about _EPR/PPS_ [disabled by default now](#2073).
Add _"foot note"-like_ mention about _EPR/PPS_ disabled by default right in the table with _Supported Hardware_, and how to enable it back.
I think it's worth adding, so new users getting _Pinecil V2_ for its main feature wouldn't be much confused why it doesn't work _out-of-the-box_.
=> Add the notice about EPR/PPS disabled by default in the main README.md

Documentation/DebugMenu.md, Translations/make_translation.py
Add time of compilation to timestamp build in _Debug Menu_.
Timestamp in _Debug Menu_ shows date of build only.
Timestamp in _Debug Menu_ shows time of build (`HHMMSS`) right next to a date of build.
While testing different builds with local changes only (i.e., can't rely on `sha id` info), I would like to have more _"differential"_ way to distinguish prepared test builds. Considering that there are a perfect spot for time even on _96x16_ screens, I hope it won't hurt. In addition, as you may know, a lot of timestamp build info for all kind of software usually …
=> Debug Menu: add time of compilation to timestamp build

source/Middlewares/Third_Party/FreeRTOS/Source/queue.c
This PR fixes a security vulnerability in xQueueGenericCreate() that was cloned from FreeRTOS-Kernel but did not receive the security patch. The original issue was reported and fixed under https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/47338393f1f79558f6144213409f09f81d7c4837.
This PR applies the same patch to eliminate the vulnerability.
**References**
https://nvd.nist.gov/vuln/detail/CVE-2021-31571
https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/47338393f1f79558f6144213409f09f81d7c4837
=> Fix: Potential Vulnerability in Cloned Function

source/Core/BSP/Pinecilv2/BSP.cpp, source/Core/BSP/Pinecilv2/configuration.h
=> Dont adjust pinecilv2 max temp by Coe

.github/workflows/push.yml
Update runs-on to ubuntu-24.04 to fix `upload_metadata` build step in GitHub Actions.
[Build error](https://github.com/ia/IronOSf/actions/runs/13656421811/job/38176930648): `This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101`.
Build pipeline should be fixed & restored.
[Bug report](#2096).
=> push.yml: update runs-on to ubuntu-24.04 to fix upload_metadata build step

source/Core/Threads/GUIThread.cpp, source/Core/Threads/UI/logic/HomeScreen.cpp, source/Core/Threads/UI/logic/Soldering.cpp
Disable animation between home and soldering screens if detailed view is set for both modes.
- go to settings and set detailed for idle and for soldering;
- exit from settings;
- try to switch from home screen to soldering mode back and forth;
- result: double-slide effect which is considered as a minor bug.
- smooth non-animated transition between home & soldering.
- [Original bug report](https://github.com/ralim/ironos/issues/2076);
- @discip [comment clarifying original bug report](https://github.com/Ralim/IronOS/pull/2100#issuecomment-2705007036).
=> Disable animation between home and soldering screens if detailed view is set for both modes (probably a finally proper fix for #2076)

Translations/make_translation.py
Update debug time stamp according to the official recommendation from reproducible builds initiative by @paulfertser [suggestion](https://github.com/Ralim/IronOS/pull/2075#issuecomment-2655952051).
There is a build timestamp already, but the implemented approach doesn't consider [reproducible builds concept](https://reproducible-builds.org/docs/source-date-epoch/).
As @paulfertser suggested, the implementation of build stamp has been updated according to [the official recommendations](https://reproducible-builds.org/docs/source-date-epoch/#reading-the-variable). …
=> Update debug time stamp according to the official recommendation from reproducible builds initiative by @paulfertser suggestion

.github/workflows/push.yml, Makefile
Add diff output for python linter if there are some warnings.
If there is a warning about python code style, then it will be just a generic summary warning, so to fix a code style, a contributor has to enable `--diff` option, run tests again, fix code style, run tests again, and remove `--diff` option.
Add `--diff` option by default to build scripts, so just like in case with `clang-format`, a contributor could see file names and lines of code related to a warning.
Suggested approach makes workflow more convenient.
=> Makefile: add diff output for python linter if there are some warnings

Documentation/Logo.md
- [✓] The changes have been tested locally
- [✓] There are no breaking changes
img2logo.py has IntelHex as a dependency which is not installed by default with Python3 or Pillow and so should be specified explicitly in the instructions, which this PR does.
Currently the documentation does not explicitly list IntelHex as a dependency.
It adds IntelHex as an explicit dependency and makes minor grammatical changes to the documentation.
=> Add missing dependency

source/Makefile
Bug fix for local compilation
Local compilation fails when the $(CURDIR) variable contains spaces
Compilation succeeds normally
I've also wrapped $(OUTPUT_DIR) to be safe, but I haven't looked specifically for other places where this could cause an issue.
I only tested this for one pair Language-Model, and did not test it in docker container, but I'd be really surprised if it would cause an issue.
=> Added support for spaces in directory names
